### ISSUE TITLE
doesn't play nicely with spaces (10.6)

### ISSUE THREAD

**Issue by herzi** [keycastr/keycastr#1]
On 10.6, the visualization only appears on the space that that KeyCastr has been launched on, when I switch the space, the visualization doesn't show up anymore, unless I switch back to exactly that space.

**Comment by ELLIOTTCABLE** [comment]
As a daily-basis Mac user, it should definitely appear in all Spaces by default. ‘Overlays’ aren't expected to act like normal windows.

**Comment by gitfoxi** [comment]
I had a little problem with this because key caster was not appearing in my dock. I guess you have to drag it in from the applications folder.

**Comment by RichardBronosky** [comment]
@gitfoxi Have you tried the steps I mention above?

**Comment by gitfoxi** [comment]
Yes and the steps works pretty well thanks. It was just the first step:

> In Keycastr preferences, enable "Display KeyCastr icon" in the dock

That didn't work. The icon just didn't show up in the dock when I did that. So I had to drag it in from the applications folder. And then I was able to complete the steps and worked fine.

**Comment by akitchen** [comment]
This is out of date and can be closed.
