### ISSUE TITLE
Enhanced options for displaying the "Shift" key

### ISSUE THREAD

**Issue by texjer** [keycastr/keycastr#104]
In the default theme, is there a way to show the "Shift" key as its own shortcut rather than simply capitalizing letters?  There some programs that use the "Shift" key as a shortcut.

**Comment by zbstof** [comment]
Double-shift is 'search everywhere' in IntelliJ family of products: IntelliJ IDEA, PyCharm, WebStorm.

**Comment by akitchen** [comment]
It would be nice to include a fix for #162 as a part of this

**Comment by akitchen** [comment]
The original request has been satisfied for some time by the option to display all modified keys.
