### ISSUE TITLE
can't display any charater!!!

### ISSUE THREAD

**Issue by yyanruo** [keycastr/keycastr#109]
mac high sierra 10.13.3
key can't display any character  when i use it, need help!!!!!!!!

**Comment by yyanruo** [comment]
<img width="683" alt="screen shot 2018-03-29 at 23 34 59" src="https://user-images.githubusercontent.com/21986668/38098139-d0bdd3fe-33a9-11e8-9d9c-5d27a4acd5b6.png">
press "command + shift + 4" to get screenshot, but not display "4"

**Comment by johngrib** [comment]
I got the same situation in Catalina.

**Comment by fdorado985** [comment]
Same Issue here Big Sur 11.5.2

**Comment by vict0rsch** [comment]
Same issue (only modifier keys) on Mojave 10.14.6

**Comment by SwJay** [comment]
Any updates now?

**Comment by fdorado985** [comment]
Same question... I don't know why my previous question was closed when it wasn't working either
