### ISSUE TITLE
Add fn keys to Svelte Visualiser

### ISSUE THREAD

**Issue by gowtham-sai** [keycastr/keycastr#111]
I really appreciate the effort you put in making this. It will be really good if you can give choice to add modifier keys in Svelte Visualiser. 

Or request to add fn keys as a modifier in Svelte Visualiser.

![image](https://user-images.githubusercontent.com/8710113/39854044-583c8726-5443-11e8-9abf-78ffd70c5ee8.png)

Currently, I see fn key is not shown as a modifier. I would like to request this as a feature. Though I never worked on Object C, I can give it a try and contribute if you guys help me. 

Thank you :)

**Comment by gowtham-sai** [comment]
IMHO I prefer to see only function key presses when somebody is pressing f1, f2 keys and etc. But with the latest mac, when function keys are swapped, if you think it is good to show other keys presses that are swapped in place of fun keys (for ex: chrome home keys when using chrome, if somebody presses it) you can show that as well. 

![image](https://user-images.githubusercontent.com/8710113/40170983-a44c8df6-59e7-11e8-9897-db672ceacb17.png)


But I prefer showing only fn keys, because when sombody presses chrome home button, they mean to go to chrome home page, but not mean to press f5 key.

**Comment by lqez** [comment]
@akitchen I'm not sure about showing `fn` status. If you think it could be worth to make it, I'll update the previous PR #112.

**Comment by akitchen** [comment]
I don't believe this is something that is useful to implement; at the end of the day, we care about (and display) F keys like F2, F8, etc.  Whether the user needed to press the fn accessory key to provide that input isn't really relevant, as it's a personal preference whether to use the Function key row as F-keys vs. "App Control" keys. 

We shouldn't clutter up the Svelte visualizer for this, but in theory the visualizer abstraction is pluggable, so someone could add their own visualizer if they want to customize the behavior.

**Comment by lqez** [comment]
Thanks @akitchen !
