### ISSUE TITLE
[Question] Is there anyway to get the strokes shown on every full screen?

### ISSUE THREAD

**Issue by hanglearning** [keycastr/keycastr#115]
Just as the title says. Since say when I made Chrome full screen, I couldn't get the strokes to display.

Thanks!

**Comment by akitchen** [comment]
this works in the latest release - please upgrade and give it a try!

**Comment by nwg** [comment]
Hm, i am using the 0.9.0 zip release and this is not working for me. The capture thing hides behind the full screen. As soon as i turn full screen off for firefox it shows again. It is behind the window, it seems.

**Comment by nwg** [comment]
Also, is this supposed to also show when i go into mission control? It would be cool if it worked and showed up in absolutely every place you could go so you could make videos demonstrating bugs and stuff in different places like mission control.

**Comment by nwg** [comment]
I rebooted my system for an upgrade to Big Sur 11.3.1. I was running the latest 11.2 before that.

Fullscreen is working now. I don't know if it was the reboot or the upgrade that fixed the problem.

Mission control does not show the keys, but i don't think that was ever supported, so everything ok on my end for now.
