### ISSUE TITLE
Cannot remove shortcut for toggle casting

### ISSUE THREAD

**Issue by yangg** [keycastr/keycastr#121]
After clear shortcut, single keystroke `a` becomes the shortcut, when you type anything includes `a`, say "alone" will start or stop casting.

ps: I just install keycastr via `brew cask`, and it's latest version available

**Comment by martin-martin** [comment]
I'm having the same issue. Preferences look like this now and there doesn't seem to be a way to change it away from the `a` button:

![screenshot 2019-03-03 at 00 12 49](https://user-images.githubusercontent.com/12371494/53684505-3275d200-3d49-11e9-8303-56b1bb97992d.png)

**Comment by martin-martin** [comment]
I think this issue can be closed, since there seems to be a more active thread on the same issue [over here](https://github.com/keycastr/keycastr/issues/105).

**Comment by akitchen** [comment]
Closing in favor of #105 ; this is fixed on the main branch via the MainMenu nib updates, and will be part of the next release.
