### ISSUE TITLE
[brew cask] macOS Sierra error 'quarantinePropertiesKey' is only available on OS X 10.10 or newer

### ISSUE THREAD

**Issue by CanRau** [keycastr/keycastr#125]
As the title hopefully suggested I'm on macOS Sierra 10.12.6 trying to install KeyCastr using `brew cask` and getting this error right after it downloaded the .zip

```
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:29:30: error: 'quarantinePropertiesKey' is only available on OS X 10.10 or newer
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:29:30: note: add 'if #available' version check
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^
Error: Failed to quarantine /Users/Can/Library/Caches/Homebrew/downloads/485be960d3588025ca2c53c6393d956f741220afe6c389f0e446b5770e25ec03--KeyCastr.app.zip. Here's the reason:
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:29:30: error: 'quarantinePropertiesKey' is only available on OS X 10.10 or newer
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:29:30: note: add 'if #available' version check
      forKey: URLResourceKey.quarantinePropertiesKey
```

**Comment by akitchen** [comment]
Just seeing this now; sorry for the delay @CanRau 

I'm not so sure this is an issue in KeyCastr; it appears to be an issue in brew cask itself. Have you search the issue list there for anything similar? 

Closing for now; please reopen if there is an issue with KeyCastr itself preventing installation. Thank you

**Comment by CanRau** [comment]
Hm don't remember what I did back in the days^^ but it might be fixed in the latest release and I just realized that the error posted above does actually look more coming from cask than KeyCastr^^
Thanks for replying and closing.. 👍
