### ISSUE TITLE
Remove GPU Dependency

### ISSUE THREAD

**Issue by Wdavery** [keycastr/keycastr#126]
The app runs with a GPU dependency on Macs with multiple GPUs installed, like MacBook Pros. It should not need this.

**Comment by akitchen** [comment]
hi @Wdavery could you please elaborate? Much of this code is quite old and in need of modernization.

Thanks for opening an issue!

**Comment by Wdavery** [comment]
I should've used standard macOS terminology, it "Requires high-performance GPU" in activity monitor. I don't know the exact fix but I believe it's a very simple one line thing.
A lot of old apps have this problem, because it was only added to macOS in the last 5 versions or so.

<img width="1072" alt="screen shot 2018-10-04 at 7 52 52 pm" src="https://user-images.githubusercontent.com/12989893/46509239-8a96bf80-c80f-11e8-9cd6-6804e82918bf.png">

**Comment by Wdavery** [comment]
I've found these two articles which I believe are the fixes.

https://developer.apple.com/library/archive/qa/qa1734/_index.html

https://developer.apple.com/library/archive/technotes/tn2229/_index.html

**Comment by gitConel** [comment]
edit info.plist
Used GPU memory: 0%

Thanks You!

**Comment by Wdavery** [comment]
Just fixed it for myself too, works great. 
Two lines in the info.plist

`<key>NSSupportsAutomaticGraphicsSwitching</key>`
`<string>True</string>`

**Comment by akitchen** [comment]
Fixed in v0.9.8
