### ISSUE TITLE
password should not display 

### ISSUE THREAD

**Issue by wuxiaoxiaoshen** [keycastr/keycastr#128]
Hi, the keycastr should not display When I enter my password，Is there one setting  hiding it?

**Comment by tuananh** [comment]
display only command keys?

**Comment by CharlesLiuyx** [comment]
You can turn it off by shortcuts before enter the password. Turn it on when finish it.

**Comment by akitchen** [comment]
when entering text in a proper password field, the events are not send to keycastr.
