### ISSUE TITLE
Default Visualizer does not work

### ISSUE THREAD

**Issue by mauris** [keycastr/keycastr#13]
I'm pleased to share that the app works on OS X 10.10 beta 3. The Accessibility privacy permission was a little confusing and a lot of manual work though.

However, the "Default" visualizer does not show up. The alternate one "Svelte" does show up.

**Comment by paulirish** [comment]
@mauris i experienced this for a while. Fixed similarly to you, bump up the fontsize like crazy.. it appears at the edge of the screen, then drag it to elsewhere on the screen.

**Comment by aaronshaf** [comment]
I had to crank up the font as well and then drag it.

**Comment by phanimahesh** [comment]
Can confirm both the issue and the workaround.

**Comment by akitchen** [comment]
This is happening because of a bad default frame in that build of keycastr.

This is fixed on master, new version coming soon

**Comment by akitchen** [comment]
This is similar to #19
