### ISSUE TITLE
become "identified developers"

### ISSUE THREAD

**Issue by maxheld83** [keycastr/keycastr#133]
macOS won't let me open "KeyCastr.app" because it comes from an unidentified developer:

<img width="419" alt="keycastr" src="https://user-images.githubusercontent.com/5372770/50846871-7adbc980-1370-11e9-88af-eaf68e0d3f51.png">

I understand that this is just macOS [Gatekeeper](https://en.wikipedia.org/wiki/Gatekeeper_(macOS)), and I know I can [override this warning](https://support.apple.com/en-us/HT202491), but it'd still be nice to have a bit more peace of mind here.

I'm not an Infosec person, but since keycastr requires full accessibility access and is kindof a keylogger, it seems like software that should be a bit safer.

**Comment by akitchen** [comment]
Thank you for commenting on this. Your point is well-taken and this is in the works. One thing to note is that KeyCastr is completely open-source and does not use any networking component, which should provide some reassurances.

**Comment by akitchen** [comment]
Quick update: this is in progress, but I've been wrestling with Apple's notarization upload flow, which doesn't seem to work for my Apple ID. I'm aiming to get this in the next release as it's increasingly important for newer versions of macOS (and I agree with your original post)

thanks for your patience!

**Comment by akitchen** [comment]
Fixed in 0.9.7
