### ISSUE TITLE
Shift+arrow left/right MAC = ?

### ISSUE THREAD

**Issue by ImDino** [keycastr/keycastr#138]
I found what would supposedly be a fix but I can't find those lines in any file, and I can't find "KCKeystrokeTansformer.m".

https://github.com/keycastr/keycastr/issues/106#issuecomment-397196699

I use a macbook pro, wireless apple keyboard.

Please help!

**Comment by Mark2Mark** [comment]
+1

**Comment by bofeiw** [comment]
+1

**Comment by akitchen** [comment]
Combinations of Shift key with arrows, enter/return, esc, and delete key are all problematic.

I'm happy to review a PR if it fixes all of these, but I'm also thinking about a fix for the next version.

asdasdasd
asdasdasd

**Comment by akitchen** [comment]
Duplicate of #106 and fixed on master
