### ISSUE TITLE
Add tags for releases and attach binaries

### ISSUE THREAD

**Issue by interstateone** [keycastr/keycastr#14]
Hey, this is a great app that does exactly what I was looking for today! :smile:

This is a grunt-work issue. Would it be possible to add a tag for the latest release version at the right commit (which will show up in the releases section of the project) and then attach the build (currently linked to in the README to that release? This might make it more clear for people where to download the app, at least I usually look at the releases tab for source and binaries at a certain tag.

Thanks!

**Comment by akitchen** [comment]
This is done now for v0.8.4 - give it a try!  Thanks
