### ISSUE TITLE
Shifted Forward Delete key ⌦ shows as unknown ? Glyph

### ISSUE THREAD

**Issue by toootone** [keycastr/keycastr#153]
Delete key is ⌫, forward delete is ⌦, but _shifted_ forward delete shows as a boxed question mark indicating, I guess, an unknown character.  I have a full mac keyboard with number pad and home, end, page up, page down keys section including the forward delete key.  I use a key combination in Adobe Premiere for ripple delete: ⇧⌦ which poses 2 problems for KeyCastr: 1) Shift Glyph doesn't show at all (See my comment on @akitchen 's [issue](https://github.com/keycastr/keycastr/issues/140) about shift modifier behaviour for my thoughts on a "menu style" mode for how to handle shift and key labels), and 2) shifted forward delete shows as a boxed question mark.
![image](https://user-images.githubusercontent.com/21961179/69660366-cad58480-1045-11ea-9364-6b3002a3a17b.png)

**Comment by akitchen** [comment]
I'm currently on a laptop but I'm not surprised there could be an issue here. Our handling of shifted key combos needs improvement. Assuming this is true, I'd call it a bug

**Comment by getvictor** [comment]
`Shift + F1` shows up as a question mark for me. Such key combinations are used in some computer games. Seems like the same issue.

**Comment by Jotto79** [comment]
Shift Left/Right/Up/Down are all question marks

**Comment by akitchen** [comment]
All of these cases were fixed incidentally in v0.9.10
