### ISSUE TITLE
IRC for collaborators / contributors

### ISSUE THREAD

**Issue by lqez** [keycastr/keycastr#16]
I joined an IRC channel `#keycastr` on freenode.
Please join on http://webchat.freenode.net/?channels=keycastr. :)

**Comment by neodevelop** [comment]
I left some messages on IRC, someone attending?

**Comment by vermiculus** [comment]
for the record, [gitter](https://gitter.im/keycastr/keycastr) is a *fine* chat client based on github repositories (and thusly integrated). there is irc access as well.

**Comment by neodevelop** [comment]
yeah! but 404 when I try to access the chat.. :)

**Comment by vermiculus** [comment]
@neodevelop That's because the owner of the repository has to create it :smile: I don't remember going through any special steps -- it was so seamless that I've no recollection of it (perhaps just visited the homepage) -- but the full docs can be [found here](https://gitter.zendesk.com/hc/en-us).

**Comment by neodevelop** [comment]
Sorry but...

[image: Imágenes integradas 1]

2015-05-18 12:51 GMT-05:00 Sean Allred <notifications@github.com>:

> @neodevelop <https://github.com/neodevelop> That's because the owner of
> the repository has to create it [image: :smile:] I don't remember going
> through any special steps -- it was so seamless that I've no recollection
> of it (perhaps just visited the homepage) -- but the full docs can be found
> here <https://gitter.zendesk.com/hc/en-us>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keycastr/keycastr/issues/16#issuecomment-103147802>.
>



-- 
*Dev. José Juan Reyes Zuñiga*
MakingDevs / @makingdevs
*http://makingdevs.com <http://makingdevs.com>*
*Tel.: 556 - 363 - 8147*
*Cel.: 551 - 850 -3073*
*Twitter: @neodevelop*

**Comment by vermiculus** [comment]
I'm not sure I understand…

**Comment by zxqfox** [comment]
If we need some chat here, better to use gitter.im. It has web interface with github auth.
https://gitter.im/orgs/keycastr/rooms

**Comment by neodevelop** [comment]
I can't access or find the room

[image: Imágenes integradas 1]

2015-12-02 4:33 GMT-06:00 Alexej Yaroshevich <notifications@github.com>:

> If we need some chat here, better to use gitter.im. It has web interface
> with github auth.
> https://gitter.im/orgs/keycastr/rooms
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keycastr/keycastr/issues/16#issuecomment-161251640>.
>



-- 
*Dev. José Juan Reyes Zuñiga*
MakingDevs / @makingdevs
*http://makingdevs.com <http://makingdevs.com>*
*Tel.: 556 - 363 - 8147*
*Cel.: 551 - 850 -3073*
*Twitter: @neodevelop*

**Comment by vermiculus** [comment]
@neodevelop Your images aren't coming through.

**Comment by neodevelop** [comment]
Oh I see.
Well, actually I'm not seeing the chat room, is a non existent room...

2015-12-02 10:39 GMT-06:00 Sean Allred <notifications@github.com>:

> @neodevelop <https://github.com/neodevelop> Your images aren't coming
> through.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keycastr/keycastr/issues/16#issuecomment-161358636>.
>



-- 
*Dev. José Juan Reyes Zuñiga*
MakingDevs / @makingdevs
*http://makingdevs.com <http://makingdevs.com>*
*Tel.: 556 - 363 - 8147*
*Cel.: 551 - 850 -3073*
*Twitter: @neodevelop*

**Comment by vermiculus** [comment]
> @neodevelop That's because the owner of the repository has to create it :smile: I don't remember going through any special steps -- it was so seamless that I've no recollection of it (perhaps just visited the homepage) -- but the full docs can be [found here](https://gitter.zendesk.com/hc/en-us).

**Comment by neodevelop** [comment]
<img width="1440" alt="captura de pantalla 2018-03-28 a la s 23 00 20" src="https://user-images.githubusercontent.com/23603/38070973-d7420976-32db-11e8-9670-25464b3728ea.png">

**Comment by elia** [comment]
Added a public room named "Lobby": http://gitter.im/keycastr/Lobby
