### ISSUE TITLE
"Catastrophic Error Encountered" dialog gets in the way of Input Monitoring permissions dialog

### ISSUE THREAD

**Issue by brandonlind** [keycastr/keycastr#160]
I've used `homebrew` (v2.2.11; core revision 26e1, cask revision 07e7f1) to install the most recent version of KeyCastr (v0.9.8). I'm running macOS 10.15.3 on a 2019 15-inch 8-core MacBook Pro.

However, when I open KeyCastr I get a pop-up that says Catastrophic Error Encountered (first screenshot below).

I've tried uninstalling via `homebrew` + removing from SysPrefs>Privacy>Accessibility before reinstalling and reopening, but I get the same message. I've tried removing from Accessibility and readding, but get the same message. In both cases, KeyCastr has had Accessibility access (it has a blue check mark), despite error message (first screenshot).

I can't seem to add it to Input Monitoring (see second screenshot), because there is no `+` option. 

The recommendation from 2shortplanks in #89 did not work (dragging and dropping KeyCastr.app from `/Applications` into SysPrefs>Privacy>Accessibility. `/Applications` is where I can see the app being removed and added by `homebrew` via an open Finder window. Also, mac won't let me drag app into SysPrefs>Privacy>InputMonitoring.

Any ideas on how to fix? Thanks in advance!

![Screen Shot 2020-03-26 at 12 55 11 PM](https://user-images.githubusercontent.com/8821725/77690763-11d67680-6f61-11ea-8075-64da21543547.png)

![Screen Shot 2020-03-26 at 1 05 10 PM](https://user-images.githubusercontent.com/8821725/77691593-71815180-6f62-11ea-9414-91e2c5c0e258.png)

**Comment by ekilah** [comment]
i'm having the same issue with a fresh install of the 0.9.8 release.

I had 0.9.6 for a long time but it was not working properly this morning (the cast popup would not appear reliably, and would sometimes pop up with lots of keystrokes from several seconds ago occasionally). 0.9.6's update window was experiencing an issue, so I came to download it directly, replaced it with 0.9.8 when dragging to `/Applications`, and then ran into this error.

hope that extra info helps?

**Comment by brandonlind** [comment]
After installing the latest macOS update (updating to 10.15.4 from 10.15.3), KeyCastr works great! Launched without issue and is capturing keystrokes.

**Comment by wjv** [comment]
Having this issue under macOS 10.15.4. No matter how (or how many times) I grant KeyCastr access to Accessibility, it still gives the error. This happens regardless of whether I install the Homebrew cask, or download the zipped app bundle from GitHub.

**Comment by wjv** [comment]
From the system log:

```Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: io.github.keycastr, PID[46449], auid: 1789, euid: 1789, binary path: '/Applications/KeyCastr.app/Contents/MacOS/KeyCastr'}, REQ:{ID: com.apple.appleeventsd, PID[509], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}```

**Comment by cwilby** [comment]
There's nothing really catastrophic about this situation, Keycastr needs to work with accessibility services to function.

**Comment by nyaray** [comment]
I just checked and I'm getting the same error as @wjv, on macOS 10.15.4, running the latest keyCastr, installed via brew cask.

**Comment by leshill** [comment]
FWIW, adding KeyCastr to `Input Monitoring` as well seems to work.

**Comment by VKondakoff** [comment]
The same issue. Could not launch KeyCastr: "Catastrophic Error Encountered". 

> FWIW, adding KeyCastr to `Input Monitoring` seems to work.

How can one add it to "Input Monitoring"?

**Comment by leshill** [comment]
@VKondakoff It is one of the other choices in the list (in my Privacy preferences list it is directly below Accessibility).

**Comment by brandonlind** [comment]
@leshill see the second screenshot above. Even once it started working for me (after updating to 10.15.4)** there is nothing in the Input Monitoring field, nor any way to manually add an app to the field. 

**though 10.15.4 doesn't seem to be a fix-all since others with the update are still experiencing issues

**Comment by leshill** [comment]
@brandonlind Not sure why I have the standard +/- buttons and you would not.

**Comment by akitchen** [comment]
"Catastrophic Error"  isn't a very user-friendly error message, but it means that KeyCastr doesn't have the access it needs. This message will be updated in an upcoming release in an attempt to clarify what's wrong and what's needed to fix it on your machine.

Meanwhile, you can remove it from Accessibility & Input Monitoring and macOS will add it back to Input Monitoring on next startup of the app (macOS Catalina only). Otherwise you may need to remove and re-add it to the Accessibility menu yourself on any version of macOS, Catalina included. The need for this can sometimes creep back in if you've reconfigured KeyCastr's dock/menu item preferences.

I've found that restarting macOS can help flush & synchronize these permissions if things really don't seem to be working right, but the need to do that should be rare. This also helps explain why an OS upgrade seemed to help fix it.

**Comment by ekilah** [comment]
Without changing anything except restarting my computer at some point in the last week, this seems to be resolved for me. Must be that a restart after installing is necessary right now for this app. 

If this turns out to be the solution, would probably be good to suggest it somewhere in the app / on that error screen / after install. I hardly restart / shut down my mac.

**Comment by wjv** [comment]
I think @ekilah may be correct. I just left KeyCastr in the non-working state (after posting the comment above), since I didn't need it immediately. When I got back to it a couple of days later, it magically just worked. The only significant thing I did in the meantime was to reboot my Mac.

**Comment by VKondakoff** [comment]
Mine started to work after system restart too.

**Comment by leshill** [comment]
I removed KeyCastr from `Input Monitoring` and rebooted and it is working as well. Still has double ⌘␣ entries though (and only that).

**Comment by pagelab** [comment]
A simple restart also solved the issue for me.

**Comment by adrianoreis-design** [comment]
Was so frustrated with this but when i installed mine and granted access under the "Accessibility" menu it still didnt work but by going into "Input Monitoring" it worked. Here is a quick gif showing what i did:

![keycastr-fix2](https://user-images.githubusercontent.com/57875908/88722581-7c591800-d0f5-11ea-91ef-c4f50e0565ac.gif)

**Comment by akitchen** [comment]
I have noticed that the legacy permissions error dialog (the "catastrophic error" message) interferes with the new system dialog for Input Monitoring, making this onboarding step extra confusing and error prone on 10.15+. We'll need to address this in a way which doesn't break 10.14 and previous OSes in the next version of KeyCastr.

For now -- drag the keycastr "Catastrophic Error" dialog to the side and click on the system dialog about Input Monitoring instead, and everything should be "fine"

**Comment by akitchen** [comment]
-> #182
