### ISSUE TITLE
Shift + direction key is unrecognized

### ISSUE THREAD

**Issue by jsphkm** [keycastr/keycastr#162]
When typing shift with any direction key, that key combination is unrecognized, and shows an icon that has a question mark inside a square:

<img width="96" alt="Screen Shot 2020-04-09 at 5 01 26 PM" src="https://user-images.githubusercontent.com/28643797/78950583-0cf6e400-7a84-11ea-9aea-14c645a25c7a.png">

**Comment by ashugeo** [comment]
I think this and #138 are duplicates of #106.

@akitchen any progress on this? 🙂  Being able to display Shift + direction key strokes would be lovely. I would love to help, unfortunately I won't be able to make a pull request as I don't know C! 😬  But maybe we can help with thoughts if you need any? (see https://github.com/keycastr/keycastr/issues/140#issuecomment-560005953)

Thank you for this app!

**Comment by akitchen** [comment]
Yes, you're right about the duplicates @ashugeo . This is fixed on the master branch and will be in the next release v0.9.9
