### ISSUE TITLE
Show Shift as icon 

### ISSUE THREAD

**Issue by je-vallejo** [keycastr/keycastr#164]
Hi there! it would be great if SHIFT could be shown as a modifier when used with letters, instead of showing the upper-case letter. Or maybe add it as a option under preferences.
#104 already asked but it's old and there has been no movement. Another look at #140 would also be great.
Other than that great tool, thanks!

**Comment by akitchen** [comment]
#140 is a bit subtle and there might not be a zero-sum fix to address it. Totally agree with you about #104, let's keep the conversation there. Thanks!

**Comment by akitchen** [comment]
I think we'll do this as a part of #187 -- keycap mode would show the shift key, whereas input mode would show the resulting shifted input key.

**Comment by afkaqualls** [comment]
Has there been any progress on this? I would like to bump the topic.

**Comment by akitchen** [comment]
This will be the behavior in v0.9.10, it may become toggle-able in a later release.
