### ISSUE TITLE
Doesn't display most characters

### ISSUE THREAD

**Issue by bvaughn** [keycastr/keycastr#166]
Possibly a duplicate of #109 since I'm also running Catalina, v10.15.4 (19E287)

![keycastr](https://user-images.githubusercontent.com/29597/81214269-763b1b80-8f8c-11ea-81d2-b3666b8168a9.gif)

I've configured it to show all characters:
<img width="482" alt="Screen Shot 2020-05-06 at 11 26 08 AM" src="https://user-images.githubusercontent.com/29597/81214247-6a4f5980-8f8c-11ea-9b6d-c570775e3eb3.png">

and I've given it the necessary permissions:
<img width="780" alt="Screen Shot 2020-05-06 at 11 25 43 AM" src="https://user-images.githubusercontent.com/29597/81214241-691e2c80-8f8c-11ea-9611-fdb41950ef8a.png">

FYI this is version 0.9.8:
<img width="368" alt="Screen Shot 2020-05-06 at 11 25 24 AM" src="https://user-images.githubusercontent.com/29597/81214234-66bbd280-8f8c-11ea-874a-4c60a48ed9f3.png">

**Comment by bvaughn** [comment]
FWIW I also tried toggling light and dark modes to see if that was somehow interfering. (No difference.)

**Comment by keeferrourke** [comment]
+1, same issue for me on OS 10.15.4

**Comment by zbe-ecust** [comment]
I had the same problem before, but fixed after restarted, works fine now.

**Comment by akitchen** [comment]
@bvaughn @keeferrourke  pinging here, does this problem persist or mysteriously go away after a while? I've seen lots of complaints of the new Security & Privacy - Input Monitoring mechanism being "buggy" and no smoking gun as to whether there's a bug in the app code -- we either get events from the OS or we don't 🤷‍♂️

**Comment by bvaughn** [comment]
@akitchen Interestingly enough, I just tried it again– and it's working as I would expect.

**Comment by keeferrourke** [comment]
@akitchen I unfortunately no longer have a mac to test with :( Sorry I can't help!

**Comment by akitchen** [comment]
Closing this issue as I believe it's a transient problem with macOS, not something that can be fixed or possibly even detected on the keycastr side. I've tried adding code locally to detect when we stop receiving events, but this issue hasn't reproduced for me in a long time leading me to believe it's been addressed in a patch of macOS.
