### ISSUE TITLE
Feature Request: Show Mouse Clicks

### ISSUE THREAD

**Issue by gurjeet** [keycastr/keycastr#168]
This may be considered outside the scope of Keycastr, but bear with me.

The primary use of Keycastr for me, and I think for many other users as well, is to show the keystrokes used during a screen recording. During a screen recording, it's also very useful to explicitly show when and where a mouse is being clicked.

It would be great if Keycastr had this feature, so we didn't have to rely on other software. There are some paid software, but none FOSS ones.

**Comment by jrgong420** [comment]
+1 that would be awesome!

**Comment by akitchen** [comment]
Hey, I don't think this is necessarily out of scope for KeyCastr, in fact I agree it would be very helpful for certain kinds of screencasts. There's a lot to consider when it comes to the details of such a feature however.

The basics of this are very easy, in fact I already have something simple working on a private branch. The next step would be to show *where* the user has clicked. But there are other subtleties to consider, such as mouseDown vs mouseUp, drag, etc. This is an area where some UX design help would be very welcome, in case anyone is inspired to help out.

FYI, I've used MouseLocator for this same purpose many years ago, but I'm not sure of its compatibility with recent versions of macOS.

**Comment by dualhammers** [comment]
How would you like to collaborate on UX?

**Comment by nwg** [comment]
I am using Big Sur and when i do a screen recording in Quicktime, there is an option to show mouse clicks. They don't show while you are recording but in the generated video, a little bubble is shown emanating from each mouse click. So that is one way to show mouse clicks without using paid software.

**Comment by akitchen** [comment]
It's been a little while, but I have a set of changes in progress that somewhat emulate the results you get when including the mouse clicks in Quicktime. I'll release a new version as soon as it's in!

**Comment by gurjeet** [comment]
Looking forward to the update!

**Comment by dualhammers** [comment]
Great!

**Comment by akitchen** [comment]
This is now available in v0.9.12

**Comment by amunrarara** [comment]
I notice the actual button of the mouseclick isn't showing; I get the same icon for Right, Left, Side Buttons, Scrollwheel Button, etc. 

Possible to request the actual mouse button to be displayed?

**Comment by ccombe** [comment]
this isn't working on Sequoia 15.4 - really want to be able to capture both trackpad gestures and mouse wheel events - I am using this to record a bug video to send to a friend to show when things are not working in an app he is making.
