### ISSUE TITLE
Shadow is cutoff

### ISSUE THREAD

**Issue by janstieler** [keycastr/keycastr#177]
Hi,
the shadow behind a cast letter is cutoff on the left and bottom side:
![Bildschirmfoto 2020-08-13 um 19 55 41](https://user-images.githubusercontent.com/754880/90169875-7d4da300-dd9f-11ea-8f51-a31ac1256c85.jpg)
This is not really nice if I use it for videotutorial who see my customers.
A possibility to change the shadow would also be nice.

Cheers

**Comment by ShivamJoker** [comment]
i also notice this hope maintainers will fix it
Cause its not that big :)

**Comment by akitchen** [comment]
Yes, depending on one's color choices, the shadow in the default visualizer can look less than great. I'm removing it in the next version.
