### ISSUE TITLE
Shift + Enter should show enter key in Svelte visualizer when Display All Keystrokes is disabled

### ISSUE THREAD

**Issue by f32by** [keycastr/keycastr#179]
Version: 0.9.8
OS: macOS 11.0 beta 9

If I enable 'Display only command keys' in Preferences, KeyCastr shows nothing when Shift+Enter is pressed.

![GIF](https://s8.gifyu.com/images/ezgif.com-video-to-gif46263bed6942850a.gif)

**Comment by Zodiase** [comment]
The "Svelte" visualizer has the same problem.

![Screen Recording 2020-11-17 at 4 28 55 PM](https://user-images.githubusercontent.com/1815174/99466983-42a15c80-28f2-11eb-87f3-3a84a2052387.gif)

**Comment by akitchen** [comment]
This issue is fixed in the default visualizer as of v0.9.10 but still exists in the Svelte visualizer. I'll adjust the title.
