### ISSUE TITLE
"Enable access for assistive devices and applications

### ISSUE THREAD

**Issue by alexhernandez** [keycastr/keycastr#18]
When activating app, even with access for assistive devices enabled for Keycastr, the application errors out and quits. See screenshots.
![screen shot 2014-11-17 at 4 57 12 pm](https://cloud.githubusercontent.com/assets/2424355/5080852/d3526cd0-6e7a-11e4-907e-817560167473.png)

![screen shot 2014-11-17 at 4 55 35 pm](https://cloud.githubusercontent.com/assets/2424355/5080829/9714c8e4-6e7a-11e4-9a5b-bdd77c0501e0.png)

**Comment by paulirish** [comment]
what worked for me:

* Put keycastr.app in your Applications folder
* open up the security/privacy/accessibility preferences that are in the top screenshot (https://github.com/keycastr/keycastr/issues/18#issue-49166722)
* click the lock to unlock this pane (bottom left)
* drag the keycastr app into the app list

it seems that it's important for the app to be in `/Applications`

**Comment by jasonhemann** [comment]
For me this same error issue emerged after changing the display from Dock and Menu Bar to only Menu Bar.

**Comment by ELLIOTTCABLE** [comment]
General solution is removing it from assistive preferences, and then re-adding it, solves this problem. Can verify. (Same as @jasonhemann, happened to me after changing it to menu-bar only.)

**Comment by ashfinal** [comment]
Same issue on 10.10.2. Seems every time you change the settings, you have to re-add it to the list of assistive preferences to avoid this error. Though not a big problem, still hope guys can fix it.

**Comment by taizilongxu** [comment]
@ashfinal  Thanks,it's work!

**Comment by bcherny** [comment]
@paulirish that worked well for me on OSX 10.10.2. thanks!

**Comment by akitchen** [comment]
@ELLIOTTCABLE  is right - sometimes you have to re-add it.  In v0.8.4 the error message is updated to be more relevant for later versions of OS X.

**Comment by ELLIOTTCABLE** [comment]
Just pointing out that on two different machines, this is *still* necessary *every single time you launch*. No other app requiring accessibility access (I have … about ten?) has this issue. )=

A real fix would be ideal, and this shouldn't be closed.

(Meantime: In addition to the notice at launch-time, *until* this is fixed, you should also add a notice when changing the dock/menubar setting, as this causes a relaunch.)
