### ISSUE TITLE
Security settings are not being picked up

### ISSUE THREAD

**Issue by iamkarlson** [keycastr/keycastr#180]
Tried to install from github and brew, the same result:
<img width="532" alt="Screenshot 2020-11-25 at 11 32 31" src="https://user-images.githubusercontent.com/4534374/100215983-05e8ed00-2f12-11eb-9295-5186e6a7d887.png">

This worked when I ran the app from Downloads but when I moved it to Applications, none of the security preferences are being picked up. Accessibility settings are shown but input monitoring isn't even showing a list:
<img width="780" alt="Screenshot 2020-11-25 at 11 35 11" src="https://user-images.githubusercontent.com/4534374/100216190-49435b80-2f12-11eb-8bd0-6216ffad98ef.png">

Macos:
$> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2

**Comment by akitchen** [comment]
This is a compatibility issue with macOS 10.15+ which is fixed on master and will be in v0.9.9 coming real soon now™

**Comment by akitchen** [comment]
(it's possible to work around in the current release, but it's tricky due to overlapping dialog boxes)

**Comment by akitchen** [comment]
-> #182
