### ISSUE TITLE
[question] Paid version? Pre-order?

### ISSUE THREAD

**Issue by jrgong420** [keycastr/keycastr#185]
Hey guys

Just tried the app and love it! would love to contribute to the app development and I hope you guys are planning a premium version to secure future updates. I think it adds tremendous amount of value when creating screencasts and tutorials for staff and audiences.

Would love to preorder or donate if possible

**Comment by akitchen** [comment]
Hello - thank you for the feedback and message of support! No, we are not soliciting monetary donations for the app at this time but please do feel free to pull the code and submit pull requests. There are also issues tagged with "help wanted" which you could consider.

Cheers!
