### ISSUE TITLE
it seems that the key display out the screen on OSX 10.10.1

### ISSUE THREAD

**Issue by taizilongxu** [keycastr/keycastr#19]
I type the delete and then

![2014-12-23 12 29 12](https://cloud.githubusercontent.com/assets/4475914/5527606/e2e73c4e-8a3a-11e4-99c6-41eae5ba8b83.png)

**Comment by petrowsky** [comment]
I just tried this out on 10.10.1 and all settings in privacy are good. Application is within /Applications. I get nothing on screen. Activity monitor does show the app is running. Just nothing on screen.

**Comment by mgarciaisaia** [comment]
I'm experiencing this same problem but on OSX 10.9.5

May it be retina-related?

If I change the resolution (in Displays) and then re-launch KeyCastr, it appears on different parts of the screen.

**Comment by ashfinal** [comment]
Just install KeyCastr and really happy now. : ) and I'm on 10.10.2.
Yes, the initial position is out of screen a bit, but the point is you can drag the window to anywhere you want! Here is my experience that you can do to solve this problem:
Hold any key for a long time, you should see the windows with your typing now. Before it fades out, you can drag the window to where you want it to be.
And now you are happy to go! Problem solved!

**Comment by akitchen** [comment]
Hey @petrowsky Yes this info helps
@mgarciaisaia  I don't think it is retina related.
My experience is mostly the same as @ashfinal , but I think we should look into possible fixes for detecting a corrupted stored NSFrame, and refactor related code to be more reliable on modern OS X versions

**Comment by Grae-Drake** [comment]
Hey @akitchen, had the same problem here.  Happy to help troubleshoot if I can.

**Comment by akitchen** [comment]
There are a few issues in the code conspiring to cause this, which the changes in ddf8ed8f774a cause to manifest when installed on new machines.  

I completely agree, this needs to be fixed.  It's top-of-list for the next time I have time to dig into it.

For now, turn off "Display only command keys" and hold down a key.  Eventually the visualizer will appear and you can drag it.

**Comment by akitchen** [comment]
There are commits on master which fix this issue; will publish a new version

**Comment by akitchen** [comment]
Please try out v0.8.5 and let us know if the problem remains

**Comment by taizilongxu** [comment]
Nice, I have update the v0.8.5 and it works well in OSX 10.10.4

**Comment by akitchen** [comment]
Thanks for confirming @taizilongxu !
