### ISSUE TITLE
Automatically toggle when screensharing?

### ISSUE THREAD

**Issue by therajumandapati** [keycastr/keycastr#190]
For people who use screen share or that record tutorial videos, it would be great to have Keycastr automatically toggle on while screen sharing.

**Comment by akitchen** [comment]
This is an interesting idea. I don't expect it's something I'll be looking into any time soon but pull requests are welcome!

**Comment by akitchen** [comment]
Now that the "toggle casting" ShortcutRecorder integration is repaired in v0.9.10, at least it should be easier to toggle key casting with a keyboard shortcut of your choice...

**Comment by akitchen** [comment]
I think it's fair to say this isn't something we're going to work on. Automatically enabling KeyCastr could be surprising or even annoying to some users, so I'd prefer to keep it manual in order to ensure it is intentional. Thank you however for opening an issue.
