### ISSUE TITLE
App not working on macOS Catalina

### ISSUE THREAD

**Issue by VetaLioSTV** [keycastr/keycastr#191]
Hi guys.

![image](https://user-images.githubusercontent.com/15155286/108609164-d3e20c80-73d4-11eb-8115-378b55b176eb.png)

App seems to be instantly crashes from start and then nothing happen, however it shows in "Activity Monitor" as running process.

Also, it doesn't appear inside section "Security Privacy" -> "Input Monitoring" :
![image](https://user-images.githubusercontent.com/15155286/108609201-23283d00-73d5-11eb-92d3-4aa5ccdaa265.png)

What i already tried : 1) Download directly from "Releases" section; 2) Download/install through homebrew;

Result is the same, app not working :( !

Any suggestions ? Thanks!

**Comment by akitchen** [comment]
Maybe take a look in the General tab of that same preference pane and ensure that it is set to "Allow apps downloaded from App Store & Identified Developers" ?

**Comment by VetaLioSTV** [comment]
@akitchen  Already unlocked full access to 3rd party apps 
![image](https://user-images.githubusercontent.com/15155286/108754867-2e9f7380-754f-11eb-94c9-8d1c66e0a778.png)

**Comment by VetaLioSTV** [comment]
I had problem with one application that wasn't compatible with MacOS Catalina, after removing it keycast started as expected. Thanks,ill close that issue.

**Comment by akitchen** [comment]
Thanks for the update - glad you were able to get to the bottom of it.
