### ISSUE TITLE
应用程序无法在macOS Big sur 上调整大小和位置信息 （11.2.1版本）

### ISSUE THREAD

**Issue by mashimaroV1** [keycastr/keycastr#192]
可以运行，但是没有办法调整大小和位置等信息。

**Comment by akitchen** [comment]
https://translate.google.com/?sl=auto&tl=en&text=可以运行，但是没有办法调整大小和位置等信息%E3%80%82&op=translate

Size can be adjusted in the application preferences, and position can be adjusted by dragging it around.
