### ISSUE TITLE
Strange behavior on fn press

### ISSUE THREAD

**Issue by Loskir** [keycastr/keycastr#193]
If I press and release <kbd>fn</kbd> button, this character appears

<img width="214" alt="image" src="https://user-images.githubusercontent.com/21295738/110245876-29dab680-7f76-11eb-8662-8cfe34c361a1.png">

"Fn press" is set to "No action" in system settings
Keycastr version is 0.9, macOS version is 11.2.2

**Comment by akitchen** [comment]
Thanks for opening an issue, this is likely an uncaught side-effect of the changes in how keystrokes are translated. Will get to it in the next release -- PRs are also welcome

**Comment by akitchen** [comment]
This is fixed in v0.9.11
