### ISSUE TITLE
Space between symbols

### ISSUE THREAD

**Issue by JannikGM** [keycastr/keycastr#194]
*(I'm using the version from brew cask)*

When pressing "F12" it will be indistinguishable from simply typing "F", "1", "2" which also displays as "F12".

I just realized that I can set a low "Keystroke Delay"; regardless, it should still work when showing presses in a horizontal line.

**Comment by akitchen** [comment]
These are in fact distinguishable in the sense that "F12" appears all at once, and "F", "1", "2" appear one at a time. You've also observed that keystroke delay and other presentation details which affect this are tunable to the user's personal preference. 

This is not likely to cause much confusion in practice. I don't think this is something we'll be working to address any time soon. We might be able to do something with different spacing for F-keys and other special keys but I don't see it as a priority relative to other things we could spend time on.
