### ISSUE TITLE
Symbol for "esc" (escape) key is confusing

### ISSUE THREAD

**Issue by JannikGM** [keycastr/keycastr#195]
*(I'm using the version from brew cask)*

The Escape key will have some weird symbol that I've *never* seen before:

![Screenshot 2021-03-12 at 16 20 49](https://user-images.githubusercontent.com/72194488/110960527-22892380-834f-11eb-848c-cf7b9fa50a2d.png)

This macbook has a "esc" key on the touchbar and my physical keyboard also just has an "Esc" key.
The displayed symbol does not make any sense to me.

Instead of the symbol, I'd like to display it as "Esc" or "esc".

See https://github.com/keycastr/keycastr/issues/157#issuecomment-774105208 for the same request in another issue.

**Comment by akitchen** [comment]
This is Apple's symbol for the escape key in menu item shortcuts. For example, click the Apple menu and observe the shortcut for Force Quit.
