### ISSUE TITLE
Fn key shortcuts disallowed

### ISSUE THREAD

**Issue by jasonhemann** [keycastr/keycastr#20]
The toggle capturing shortcut bar wasn't allowing me to use one of the Fn keys (F3, if it matters) as the toggle sequence. 

It said that it was already in use by the system as a keybinding. This persisted even after I had turned off the Fn sequence is system preferences 

OS X 10.10.1
keycastr-0.8.2, installed via hombrew caskroom

**Comment by akitchen** [comment]
I think this is actually an issue in the shortcutrecorder framework that keycastr uses internally. we're on a very old version, so let's hope this is addressed once we can update it.
