### ISSUE TITLE
"command + space" appear twice?

### ISSUE THREAD

**Issue by daolou** [keycastr/keycastr#201]
![image](https://user-images.githubusercontent.com/22312092/113727897-27f84480-9728-11eb-9ee5-8025866c9852.png)

when input "command+space",it appear twice

![image](https://user-images.githubusercontent.com/22312092/113728095-56761f80-9728-11eb-84c2-98d382d90485.png)

**Comment by akitchen** [comment]
This is captured in #163 . Unfortunately the app receives two events for this key press instead of one, and we simply display it instead of special-casing it right now.
