### ISSUE TITLE
Keystrokes are not visible when Bitwarden is running in the background

### ISSUE THREAD

**Issue by darmiel** [keycastr/keycastr#202]
When Bitwarden is running in the background, the keystrokes are no longer displayed. Only when you close Bitwarden completely, the keystrokes are shown again. Is this the way it should be?

https://user-images.githubusercontent.com/71837281/117328900-605c8100-ae94-11eb-9ba1-c5cddb60673b.mov

**Comment by akitchen** [comment]
That's interesting, my best guess is that somehow keycastr isn't getting key events while Bitwarden is enabled. Not sure there's much we can do about it without being able to debug it locally, and I'm not a Bitwarden user.

**Comment by darmiel** [comment]
Looks like this is an electron thing: [app.setSecureKeyboardEntryEnabled](https://www.electronjs.org/docs/api/app#appsetsecurekeyboardentryenabledenabled-macos)
> By using this API, important information such as password and other sensitive information can be prevented from being intercepted by other processes

👉 Apple [TN2150](https://developer.apple.com/library/archive/technotes/tn2150/_index.html)

Doesn't look like there's anything you can do about it. I think that the issue can be closed with this.

**Comment by akitchen** [comment]
It sort of makes sense, if secure input mode is meant to stop other applications receiving potentially sensitive keystrokes (similar to a password entry mode).

Closing this since we're not able to do anything about it, but thank you for opening an issue and following up.
