### ISSUE TITLE
Position of keystrokes is suddenly on top left (instead of bottom left)

### ISSUE THREAD

**Issue by jmuheim** [keycastr/keycastr#204]
Since some days, the keystrokes are displayed on top left of my window:

<img width="547" alt="Screenshot 2021-05-27 at 13 25 50" src="https://user-images.githubusercontent.com/1814983/119818084-0f6a0680-beef-11eb-9b5a-a05096911fe8.png">

I think this happened because I had connected a 2nd monitor, and this kinda messed up the internal setting of KeyCastr.

Interestingly, the Svelte window is still displayed correctly on the bottom left.

How can I fix this? And make sure it won't happen again, even with a 2nd monitor attached?

**Comment by jmuheim** [comment]
Since I attached my 2nd monitor again for a presentation, the position is correct again. I don't really know the circumstances, but maybe I will find out how to "fix" it manually...

Would be glad though to know that it's fixed in the app.

**Comment by akitchen** [comment]
There are changes coming to better manage the position of the bezel over time, but for now if you change your display settings (such as unplugging your monitor or changing screen resolutions) KeyCastr will reset the default visualizer to its default position in the lower left corner.

**Comment by jmuheim** [comment]
Thank you, that's useful to know.

**Comment by jmuheim** [comment]
> if you change your display settings (such as unplugging your monitor or changing screen resolutions) KeyCastr will reset the default visualizer to its default position in the lower left corner

I just updated to the newest version. But this doesn't work: I changed the resolution of my Macbook's screen (`Scaled`, then `More Space`), but no effect still.

**Comment by jmuheim** [comment]
Ah, I just realised that I can drag&drop the position manually! I wasn't aware of that, is it a new feature?

It might be meaningful to add some hint about that somewhere in the `Preferences`.
