### ISSUE TITLE
Whenever the "a" key is pressed, KeyCastr stops casting

### ISSUE THREAD

**Issue by izhang05** [keycastr/keycastr#206]
Whenever the "a" key is pressed, KeyCastr stops casting. This occurs even if the focus is on another application.

**Comment by RobertMcReed** [comment]
I just installed keycastr and noticed the same. It appears that is the default keybind for start/stop casting. The default should probably be changed, but as an interim fix, you can bind a new hotkey from the preferences menu.

From the "General" tab, click in the "Toggle capturing:" box and then set a hotkey such as `cmd + opt + shift + a` or similar, so it doesn't accidentally get triggered.

![image](https://user-images.githubusercontent.com/20693762/121421159-b81e5a00-c922-11eb-8bf6-88d94659daeb.png)

**Comment by akitchen** [comment]
Hmm, that's strange. It could be something with ShortcutRecorder, which desperately needs some updates for recent versions of macOS (note the incompatibility with dark mode too)

I'll add this to the list for the next release; thank you for opening an issue. And @RobertMcReed is right, hopefully you can reset this by setting a new shortcut.

**Comment by izhang05** [comment]
Thanks! Changing the shortcut worked.

**Comment by akitchen** [comment]
I cleared out the user defaults for keycastr and did a fresh install, and the default shortcut on next run was set to ^⌥⌘K as expected. Please open another issue if you run into this again.
