### ISSUE TITLE
Crashed when I asked to display icon in dock

### ISSUE THREAD

**Issue by gitfoxi** [keycastr/keycastr#21]
See my comment in #1. When I selected Display keycastr icon in the dock before I had dragged the program into the dock from the finder keycastr crashed immediately and I had to track down and delete its Plist file before it would start again.

When it crashed and wouldn't start it gave me a message similar to the message it gave me before I enabled key caster in the accessibility security preferences.

**Comment by akitchen** [comment]
I tried this (on Yosemite) and it didn't crash.  What version of OS X are you on?  Can you open Console.app and see if there is a crash log?

This change in the preferences does cause the app to prompt you to allow it to restart, which could also have been confused with a crash.

This feature might not be possible on modern OS X; I would vote we remove the option select list from the preferences pane and display the icon in the menu bar by default.  The user needs to drag it to the dock if desired.

**Comment by akitchen** [comment]
On second thought, we shouldn't remove this, since the "display in dock" option is what causes KeyCastr to also show up in the cmd-tab list of active applications.  Perhaps this option needs a better name.

**Comment by gitfoxi** [comment]
I am up-to-date with my OS X versions like you are. `~/Library/Logs/DiagnosticReports` does not contain any crash dumps. I might've used the wrong word. It doesn't crash. It pops a box saying that it has detected a horrible situation that it thinks has to do with security preferences and that it's going to shutdown and then it does.

I find that I am still able to reproduce the issue when I select "in the dock".

**Comment by gitfoxi** [comment]
And since I can reproduce it I might as well give you the exact error message. 

![screen shot 2015-04-03 at 7 57 09 pm](https://cloud.githubusercontent.com/assets/584005/6991215/b909ca62-da3b-11e4-9290-b558e5645816.png)

**Comment by akitchen** [comment]
This is not a crash - this is expected.  KeyCastr is telling you that you need to grant it permission.

To do this, visit the Security & Privacy preferences pane, and open the Privacy tab.  Select "Accessibility"in the left menu and unlock the preferences pane if it is locked.  Then drag your copy of KeyCastr into the list of applications "allowed to control your computer".

This is required in order for KeyCastr to catch keyboard events.

**Comment by akitchen** [comment]
![screen shot 2015-04-03 at 9 04 45 pm](https://cloud.githubusercontent.com/assets/378648/6991368/192a251e-da45-11e4-9801-39ec31898b0b.png)

**Comment by gitfoxi** [comment]
I know what it looks like but that's not it. I did grant permission and I've been using it all day. It's when I change that setting that it gives me the message as if I had not granted  permissions which I definitely did.

**Comment by akitchen** [comment]
I've run into this issue before when upgrading or switching between development and released versions. It is normal. You will need to drag your current copy into that pane. Perhaps there is more than one copy of the app on your computer?

**Comment by L8D** [comment]
BTW, I'm getting the same issue described by @gitfoxi 
It works fine, except when I tell it to go to the dock, it crashes and displays the same error until I reinstall.
