### ISSUE TITLE
it wont allow me to change screen for the output 

### ISSUE THREAD

**Issue by gabakusa** [keycastr/keycastr#215]
i have 3 monitors and i see no watch to change the monitor where the keystrokes will be displayed
please I need some help or if the feature can be added later

**Comment by akitchen** [comment]
Have you tried dragging the window to a different monitor? It works fine with 2 screens, haven't tested with more than that.

**Comment by gabakusa** [comment]
I did not 

Best regards
Gabriel Barrandeguy

Computer Consultant
***@***.***
www.GabakUSA.com
Cellphone / WhatsApp +1-859-878-0554

**Comment by fdorado985** [comment]
Same issue for me, it is not working, I just have 1 extra monitor, I checked the option on Input Monitor privacy setting but nothing is working, should I be focusing something?

**Comment by akitchen** [comment]
You can drag the visualizer window to any monitor where you'd like to see it.
