### ISSUE TITLE
New icon should be retina-friendly

### ISSUE THREAD

**Issue by akitchen** [keycastr/keycastr#22]
The new menu bar icon is nice, but I would like to see a retina variant as well :)

**Comment by akitchen** [comment]
also there should be an inverted version which looks decent in OS X dark mode

**Comment by lqez** [comment]
Agreeeee.
But I'm still using MacBook Air(yes, non-retina), it may takes some time.
I should test it on my coworker's rMBP. :(

**Comment by akitchen** [comment]
Fixed by #34
