### ISSUE TITLE
is there any way to reset the setting of default display?

### ISSUE THREAD

**Issue by iron2column** [keycastr/keycastr#220]
<img width="403" alt="iShot2021-12-08 12 09 13" src="https://user-images.githubusercontent.com/83954171/145146763-35d0b929-aa45-4c3d-8f89-c80f3ededc39.png">

**Comment by akitchen** [comment]
You could try quitting the app & deleting all of KeyCastr's stored configuration with the `defaults` command in the terminal.

e.g., `defaults delete io.github.keycastr`

When you start up the next time, these settings would reset to the default.
