### ISSUE TITLE
num pad keys not indicated

### ISSUE THREAD

**Issue by soundflix** [keycastr/keycastr#224]
I noticed that num pad keys are not displayed differently than their main keyboard counterparts (0123456789=/*-+,).
Did I overlook something?

**Comment by soundflix** [comment]
I don't know if there's already a consensus about this.
Keyboard Maestro uses this ⊞ Squared Plus Unicode Symbol (U+229E), which I would be fine with.
I guess prepending "num" would be too verbose.

**Comment by akitchen** [comment]
There are some specific characters to represent the number pad keys when used for navigation. I'll probably add those in #296

**Comment by soundflix** [comment]
I checked the new version, num pad key characters are still the same, i.e. not different to regular?
