### ISSUE TITLE
Keycastr isnt showing up on accesibility list

### ISSUE THREAD

**Issue by B-Dawg0531** [keycastr/keycastr#225]
![Screen Shot 2022-02-08 at 7 11 38 PM](https://user-images.githubusercontent.com/99299561/153097143-8a9c1fff-9fa2-4f6c-bc86-3e40d70c06cb.png)

**Comment by B-Dawg0531** [comment]
HLP

**Comment by akitchen** [comment]
It appears you're on an older version of macOS, though you haven't provided any details.

In this case, you need to add it yourself via the trusty + button.
