### ISSUE TITLE
keycastr does not work well in multiple screens

### ISSUE THREAD

**Issue by TheOnlyAndLastOne** [keycastr/keycastr#230]
when I use an external screen, keycastr only works with one of them, I tried several times and find that keycastr works with the screen witch I first open it, it means when I want to show the keypress on the other screen, I have to quit keycastr, move to the other screen and reopen keycastr again, my sys is MacBook Pro M1, macOS Big Sur 11.2.3, I don't know if this happens on other sys, if so I wish it can be a configuration option in the later version.

**Comment by akitchen** [comment]
You should be able to drag the KeyCastr visualizer to display you like in a multi-display setup. And it will show up on any "desktop" if you are using multiple desktops on that display.

Could you describe your setup in more detail? How many displays are connected and what is the layout?

**Comment by BppleMan** [comment]
> You should be able to drag the KeyCastr visualizer to display you like in a multi-display setup. And it will show up on any "desktop" if you are using multiple desktops on that display.
> 
> Could you describe your setup in more detail? How many displays are connected and what is the layout?

I had the same problem.

I using two display.

like…

![image](https://raw.githubusercontent.com/BppleMan/image-hosting/main/20220526/截屏2022-05-26-16.67ps48976w00.webp)

**Comment by Aariq** [comment]
I can drag the KeyCastr display to my external monitor, but not if that external monitor has a fullscreen app on it.

**Comment by robin-cruk** [comment]
> I can drag the KeyCastr display to my external monitor, but not if that external monitor has a fullscreen app on it.

This might be a workaround: https://github.com/keycastr/keycastr/issues/37#issuecomment-213667782

**Comment by akitchen** [comment]
Sadly this may be a limitation with how windowing and fullscreen apps currently work in macOS. There are some subtle differences in fullscreen behaviors when you have multiple displays attached. I'll try some additional testing, but you may have better luck using only one display when you want to use KeyCastr on top of a fullscreen app.

**Comment by akitchen** [comment]
I've noticed this varies depending on the app. Other thing like apps with secure data entry seem to limit the event stream more than they used to as well (you can see an example of this by enabling secure mode in the built-in Terminal.app while using KeyCastr)

I don't think there's much that can be done here.
