### ISSUE TITLE
keys not appearing in full screen mode

### ISSUE THREAD

**Issue by sozoalvin** [keycastr/keycastr#238]
love this neat little thing! 

except I realised the keys not appearing when im in full screen or something. 

is this is bug/ intended behavior? or if i missed some something please help point me in the right direction!

**Comment by harsh-ws** [comment]
Hi @sozoalvin . can you please share the relevant details/Screenshot for the issue you're facing?

**Comment by akitchen** [comment]
Unfortunately I don't think this is possible by definition. When an app's window is in fullscreen mode, we cannot display another app's window on top of it.
