### ISSUE TITLE
Show command keys as modifying mouse clicks

### ISSUE THREAD

**Issue by AdobeWanKenobe** [keycastr/keycastr#243]
I need to demo graphics apps where command keys modify mouse clicks and drags, but in default mode KeyCastr won't display them unless used in combination with a regular key. Is this something that can be enabled or added?

**Comment by akitchen** [comment]
I completely agree this would be great. It's pretty much the next thing I'd like to add. It's mostly a matter of figuring out some sane defaults and configuration options based on what's been suggested in #228 and other issues.

**Comment by whitefxdesign** [comment]
> I need to demo graphics apps where command keys modify mouse clicks and drags, but in default mode KeyCastr won't display them unless used in combination with a regular key. Is this something that can be enabled or added?

This will certainly be a nice addition. I have a similar (if not the same) use case for Adobe InDesign that I need to demonstrate the use of pressing ⌘ + ⇧ before click-dragging an object and continuing to hold these two command keys down until the cursor has been released.

Thanks in advance!

**Comment by akitchen** [comment]
in the upcoming version, clicks plus modifiers will be shown in the currently active visualizer, if enabled.
