### ISSUE TITLE
The mouse click visualizer won't work for full screen apps

### ISSUE THREAD

**Issue by kotobuki** [keycastr/keycastr#245]
I love the mouse-click visualizer introduced in v0.9.12.

However, it seems that the visualizer works only for windowed apps. For example, I can see a circle for a mouse click on Chrome. Once entered in full-screen mode, I can't see circles anymore.

I confirmed with Chrome and Slack on macOS Monterey v12.5. I'm sorry if I missed any settings to be done.

**Comment by akitchen** [comment]
Thanks for opening an issue, I've double-checked this and I do get mouse clicks as well as the default visualizer on top of a fullscreen app. 

Are you having one and not the other, or is nothing working at all for you in fullscreen? And is there anything special to mention about the app you're using?

**Comment by akitchen** [comment]
I've re-tested this a number of times and it works fine for me (macOS Sonoma 14.x). It is possible that input events will not come through to KeyCastr if you have secure key entry enabled or another app is also handling input events via the accessibility API, and there isn't anything that can be done about it. As best as I can tell this is working fine.

**Comment by mmoole** [comment]
I am having this problem on site specific apps created by Safari. If they are set on full-screen, no mouse click visualization can be seen  🤷 (macOS 15.6.1)
