### ISSUE TITLE
Interoperability with python's keyboard library

### ISSUE THREAD

**Issue by beyarkay** [keycastr/keycastr#251]
Hi there!

Just wondering what it would take for this to work with [python's `keyboard` library](https://github.com/boppreh/keyboard)?

I want to be able to send keystrokes via the library and have keycastr display them. But what is actually happening is that the library is sending the keystrokes correctly but keycaster is displaying just an `a` for every keystroke, regardless of what I type. Is this something on the libraries side or on keycastr's side?

**Comment by akitchen** [comment]
Thanks for opening an issue. I would expect this to be supported if the events generated by this library are like any others passed to keycastr in its event tap. It could also be something on keycastr's side, if we're not observing enough input event types in the event tap (see KCKeyboardTap.m)

Do you have a simple example you could share which demonstrates the issue? Pull requests are also welcome if you happen to figure out what adjustments are needed.

**Comment by akitchen** [comment]
Assuming this is a problem with the events generated by the library you mentioned. Please reopen and/or share any interesting learnings.
