### ISSUE TITLE
Remember status when starting the app

### ISSUE THREAD

**Issue by x-magic** [keycastr/keycastr#256]
Currently the behaviour of the app is that:

- When the app starts, it will start "casting" immediately
- User can choose to stop "casting" from the icon menu
- Quit the app with "casting" stopped
- Start the app again, the "casting" starts instead of stopped

i.e. the status of "casting" is not remembered and carried on when the app restarts. 

It helps when the app starts with the Mac and user can choose whether it start "casting" at boot or not.

**Comment by akitchen** [comment]
Thank you for opening an issue about this. After thinking about it, I'm going to close it -- I don't want to add this option as it will appear the app is broken when it is not, and make troubleshooting more confusing privacy permissions more difficult.
