### ISSUE TITLE
Feature Request: Compress repeats similar to screenkey

### ISSUE THREAD

**Issue by kiryph** [keycastr/keycastr#264]
The Linux tool `screenkey` https://gitlab.com/screenkey/screenkey supports compressing repeats in following way:

> When enabled, contiguous repeated sequences are truncated after the
requested threshold. A counter of total occurrences is shown instead,
which is generally more legible.

It is more clear with this gif from https://superuser.com/a/1537680

![1sm0R](https://user-images.githubusercontent.com/371756/224973266-5da3536c-1a40-4161-87b7-8f5e163bc07b.gif)

The default threshold is 3. The feature has been introduced in version 0.9:
https://gitlab.com/screenkey/screenkey/-/blob/master/NEWS.rst

Is it possible to add a similar feature to keycastr?

**Comment by akitchen** [comment]
contributions are welcome, but given how the default visualizer currently works this doesn't really make sense.
