### ISSUE TITLE
Ability to control with AppleScript or other software

### ISSUE THREAD

**Issue by Hoofoo-WHU** [keycastr/keycastr#270]
Although set global shortcut key is used well, but sometimes it will be conflict or forget. I think if provide a way to controlled by other way like [Raycast](https://www.raycast.com/) should be nice. I checked Raycast's API [documentation](https://developers.raycast.com/examples/spotify-controls), there is a way that use AppleScript control other application, maybe other similar application could access through AppleScript too.

**Comment by akitchen** [comment]
Mis-attributed in a different commit, but I don't think we'll be addressing this so leaving it closed.
