### ISSUE TITLE
Start/Stop casting does not work with Svelte mode

### ISSUE THREAD

**Issue by alexzhaohong** [keycastr/keycastr#275]
The functionality of Start Casting and Stop Casting with Svelte mode does not match the behavior of the Default mode. In Svelte mode, when you stop casting, the Svelte snackbar will remain floating, will not emit command key combinations, but will still highlight whenever a modifier key is pressed. 

Proposed functionality: The Svelte snackbar hides on Stop Casting

PS. Not sure if there is already a Svelte Mode improvement issue The linger time for the Svelte key combinations is too fast for an audience to see it.

**Comment by akitchen** [comment]
yeah, the first part is a bug. The second is perhaps "by design" although PRs to help improve it are certainly welcome.
