### ISSUE TITLE
Arrow keys showing with fn

### ISSUE THREAD

**Issue by applebait** [keycastr/keycastr#280]
The latest version (v0.9.14) is showing the word "fn" and the direction whenever I press any arrow key.
I'm on Sonoma, Apple silicon.

![Keycastr_v-0-9-14_arrow_keys_bug](https://github.com/keycastr/keycastr/assets/44685612/5e76e36e-7b3e-420a-af69-ea661f9ee2d0)

**Comment by akitchen** [comment]
Thanks for opening an issue, I see that too. It looks like there might some tricky stuff with how the fn key modifier is sent along with events, or some other kind of bug in how they're being interpreted.

**Comment by akitchen** [comment]
Fixed in [692dc83](https://github.com/keycastr/keycastr/commit/692dc8304e635a59b6366d722ce73014ceee017d), a new build will be released soon.
