### ISSUE TITLE
It doesn't work well  on OSX 10.10.3

### ISSUE THREAD

**Issue by linnv** [keycastr/keycastr#29]
when using the default visualizer, no commands display;
when using svelte,only command with function key output like bellow:
![screen shot 2015-06-10 at 11 58 07 am](https://cloud.githubusercontent.com/assets/3351811/8074677/16af83da-0f68-11e5-8b2b-d0f330632c49.png)
Is it a bug of the app?

**Comment by akitchen** [comment]
I haven't seen this one before, but I believe it is due to how the app is receiving key events from the OS.

Is there anything interesting about your setup?  Any other apps using accessibility privacy access?

**Comment by shaneog** [comment]
Same issue for me. 
Apps using the Accessibility -> Privacy access: Dropbox, Karabiner, Moom, TextExpander

**Comment by fabianuribe** [comment]
Same issue here.

**Comment by phil-r** [comment]
Same for me ;(

**Comment by akitchen** [comment]
The svelte visualizer behavior is correct - it only displays command sequences.  The default visualizer is most likely not visible due to it being offscreen.

see https://github.com/keycastr/keycastr/issues/19
