### ISSUE TITLE
Error: 'display words' pop-window abnormal behavior

### ISSUE THREAD

**Issue by JunSilckTar** [keycastr/keycastr#295]
Hi

Thank you for your work

Sonoma 14.5
I got a error:
When switching between system windows, there is a probability that the 'display words' pop-window will be displayed incorrectly, even if Toggle Capturing is off

the Error most happen on switch Window

![截屏2024-05-30 10 05 52](https://github.com/keycastr/keycastr/assets/103525955/0a508c48-a3ae-40f2-8bb9-2c5d75fa6aa8)

**Comment by JunSilckTar** [comment]
Looks like a conflict between the app animation and the system animation

Tell me where to find the logs, I can post it

**Comment by akitchen** [comment]
Is this the same as #286 ?
