### ISSUE TITLE
cmd + space shows up twice

### ISSUE THREAD

**Issue by Aariq** [keycastr/keycastr#298]
Whe I use cmd + space, the shortcut shows up twice on my screen if I press the spacebar quickly.

**Comment by akitchen** [comment]
Thanks for opening an issue, can you confirm you are on an Intel/x86_64 machine?

This is likely the same issue as #163

**Comment by Aariq** [comment]
Yup, this is a duplicate.  Sorry!

**Comment by akitchen** [comment]
No problem, thank you
