### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by kosekidev** [keycastr/keycastr#300]
Hi !
I use "FRPC" layout on my Mac, and keycastr show wrong keys sometimes :

\# key show : Option"
{ show : Option'
} show : Option=
...

Layout maybe not take in count ?

**Comment by akitchen** [comment]
Hello, thank you for opening an issue.

Looking at your keyboard layout, KeyCastr is displaying the expected output. It is displaying the modifiers plus the keycap for your layout. On a French PC keyboard, `'` is the keycap for `{` (when `⌥` is applied), and `=` is the keycap for `}` (when `⌥` is applied). If I type `⌥3` on a US English keyboard to produce `£`, KeyCastr will display `⌥3`. 

Displaying keycaps vs. the result of applying modifiers (expected output) is a tricky topic, which is discussed in #187 . Switching it by default for all usage results in other unexpected results, so it needs to be a user-facing option.
