### ISSUE TITLE
Modifier keys not displayed on Intel macs

### ISSUE THREAD

**Issue by Aariq** [keycastr/keycastr#303]
I could be mistaken, but I thought KeyCastr previously displayed shift and option key symbols.  In the latest release they seem to be missing.  E.g. this is what is shown with shift option command g when "command keys only" or "all modified keys" are selected as options.
  
<img width="115" alt="Screenshot 2024-08-28 at 10 01 40 AM" src="https://github.com/user-attachments/assets/3e29cace-0356-4f6f-8b37-62bd15afd0d6">

**Comment by Aariq** [comment]
Yeah, just downgraded and confirmed that this is a bug in the most recent release (v0.10.0)

**Comment by akitchen** [comment]
This certainly doesn't seem right. In addition to the modifiers, any command sequence (ctrl or cmd modifier) should be capitalized.

Given you said you downgraded to v0.10.0, I have to wonder about your local setup. Have you also been running an experimental version of your own? How did you "downgrade"? Is there anything else unusual about your setup, like a custom keyboard layout?

Please remove KeyCastr from the Input Monitoring list in the Privacy and Security settings pane, make sure you are starting the intended copy of the app, re-enable the permissions when prompted, and try again.

**Comment by Aariq** [comment]
When I say "downgraded" I mean I installed the app from the download here: https://github.com/keycastr/keycastr/releases/tag/v0.9.18

If I replace the KeyCastr app with the release here: https://github.com/keycastr/keycastr/releases/tag/v0.10.0 and do as you suggested, I get the behavior reported above.

**Comment by akitchen** [comment]
Very strange. Do you have other apps in the Input Monitoring or Accessibility list? And what is displayed with control-g instead of command-g? Can you share other details about your system, i.e. are you on an Intel or Apple processor etc.?

**Comment by Aariq** [comment]
Intel macbook running macOS Sonoma (14.6.1).  I turned off other apps input monitoring (the only other one was OBS) and the problem persists with this version.  control-g shows the correct shortcut (^g), but control-shift-g shows the same thing (the shift is not displayed). Command-control-g works as expected. It seems to be just option and shift that don't show up and that the letters are lowercase.

**Comment by akitchen** [comment]
Thanks for that info. I just fired up my older Intel mac and saw this as well. I'll figure out a fix soon.
