### ISSUE TITLE
Crash on OS X 10.7.5 (should at least tell user platform is not supported)

### ISSUE THREAD

**Issue by danpovey** [keycastr/keycastr#31]
--
Process:         launchd [58070]
Path:            /Users/USER/Downloads/KeyCastr 2.app/Contents/MacOS/KeyCastr
Identifier:      net.stephendeken.KeyCastr
Version:         ??? (???)
Code Type:       X86 (Native)
Parent Process:  launchd [53029]

Date/Time:       2015-08-13 16:17:19.256 -0700
OS Version:      Mac OS X 10.7.5 (11G63b)
Report Version:  9

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x000000008fe01030

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x00000000  ebx: 0x00000000  ecx: 0x00000000  edx: 0x00000000
  edi: 0x00000000  esi: 0x00000000  ebp: 0x00000000  esp: 0x00000000
   ss: 0x00000023  efl: 0x00010202  eip: 0x8fe01030   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x00000000
  cr2: 0x8fe01030
Logical CPU: 0

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 33166
    thread_create: 0
    thread_set_state: 0
-----
results of trying to debug it:

mac:Contents: gdb  /Users/danielpovey/Downloads/KeyCastr\ 2.app/Contents/MacOS/KeyCastr
GNU gdb 6.3.50-20050815 (Apple version gdb-1708) (Thu Nov  3 21:59:02 UTC 2011)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...unable to read unknown load command 0x80000028

warning: Unable to read symbols for /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (file not found).

warning: Unable to read symbols from "CoreGraphics" (not yet mapped into memory).
Reading symbols for shared libraries ........... done
unable to read unknown load command 0x80000028

(gdb) r
Starting program: /Users/danielpovey/Downloads/KeyCastr 2.app/Contents/MacOS/KeyCastr 
warning: The target crashed on startup, maybe the shell is crashing.
"Try set start-with-shell 0" to workaround.
Abort trap: 6

**Comment by akitchen** [comment]
Hi there,




Can you try debugging as i386? I'm curious if there is any useful information to be found.

**Comment by danpovey** [comment]
Perhaps this is what you meant?


mac:Contents: gdb -arch i386  /Users/danielpovey/Downloads/KeyCastr\
2.app/Contents/MacOS/KeyCastr
GNU gdb 6.3.50-20050815 (Apple version gdb-1708) (Thu Nov  3 21:59:02 UTC
2011)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain
conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...unable to read unknown
load command 0x80000028

warning: Unable to read symbols for
/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
(file not found).

warning: Unable to read symbols from "CoreGraphics" (not yet mapped into
memory).
Reading symbols for shared libraries ........... done
unable to read unknown load command 0x80000028

(gdb) r
Starting program: /Users/danielpovey/Downloads/KeyCastr
2.app/Contents/MacOS/KeyCastr
warning: The target crashed on startup, maybe the shell is crashing.
"Try set start-with-shell 0" to workaround.
Abort trap: 6
mac:Contents: set start-with-shell 0
mac:Contents: gdb -arch i386  /Users/danielpovey/Downloads/KeyCastr\
2.app/Contents/MacOS/KeyCastr
GNU gdb 6.3.50-20050815 (Apple version gdb-1708) (Thu Nov  3 21:59:02 UTC
2011)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain
conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...unable to read unknown
load command 0x80000028

warning: Unable to read symbols for
/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
(file not found).

warning: Unable to read symbols from "CoreGraphics" (not yet mapped into
memory).
Reading symbols for shared libraries ........... done
unable to read unknown load command 0x80000028

(gdb) set start-with-shell 0
(gdb) r
Starting program: /Users/danielpovey/Downloads/KeyCastr
2.app/Contents/MacOS/KeyCastr
warning: The target crashed on startup, maybe the shell is crashing.
"Try set start-with-shell 0" to workaround.
Abort trap: 6
mac:Contents:

**Comment by akitchen** [comment]
Hmm, I don't see anything of interest. This is what caught my eye:




This GDB was configured as "x86_64-apple-darwin"...





It might not be relevant.




Perhaps more importantly, is there any observable behavior before the crash? Could this be due to accessibility permissions?




I'm not aware of any newer API used by KeyCastr, and it used to run fine on 10.5. I no longer have a 10.7 machine and I'm not inclined to set one up, but if you're able to come up with anything more useful (or try a debug build from source) I would like to hear what you are able to discover. I am not near a computer for some weeks but perhaps this is due to the min deployment target having changed at some point?

**Comment by danpovey** [comment]
my gdb comes from port, I think.
It doesn't do anything before it crashes.
Dan

**Comment by akitchen** [comment]
I'm admittedly foggy on this, but the current build is built with clang/LLVM and probably doesn't support the legacy runtime. Your best bet might be to clone the project and build with the last developer tools released for your OS. Sorry I can't be more helpful.

**Comment by akitchen** [comment]
The min supported version of OS X will be raised in the next release, as it is on master
