### ISSUE TITLE
Bug: It always automatically types what I previously typed in when I quit KeyCastr

### ISSUE THREAD

**Issue by 27-Iseri** [keycastr/keycastr#311]
As the video shows, I was typing some words in the text. After I quited KeyCastr, it automatically repeated what I had previously typed in, even if I did nothing.
https://github.com/user-attachments/assets/be49fb4e-9dda-4d8b-9080-434eef422f45

**Comment by akitchen** [comment]
Hi, thanks for opening an issue about this with a video demonstration. This bug has been around for a while, referenced also in #72 . 

I have been able to figure out what is causing this, but I'll need to think a bit about the best way to handle it. It should be fixed in the next release.
