### ISSUE TITLE
Stopped to work when connecting a second screen

### ISSUE THREAD

**Issue by vichug** [keycastr/keycastr#36]
Hi,
When i use this app on my machine it works flawlessly (osx 10.10.5). However the other day i connected a retroprojector, the screen mirroring was on and the resolution was changed, and it stopped to work. It may be related to https://github.com/keycastr/keycastr/issues/19 ; i don't know as i can't test it anymore now. I tried to quit and relaunch Keycastr, it din't solve, however i think it might have been better when i rebooted the computer.

**Comment by akitchen** [comment]
I suspect with the resolution change the visualizer was simply offscreen.  I think if you restarted keycastr it would reposition itself for the new resolution.

Could you update it and try again?

**Comment by vichug** [comment]
Hey. Now i don't think i saw the bug again... anyway, if i open keycastr after connecting the screen, it's all good :)
i would try again with last version but i have no idea about compiling, sorry...

**Comment by akitchen** [comment]
@vichug could you try again with the latest version from brew cask or the versions page?

**Comment by vichug** [comment]
alas, now i don't have a setup with a second screen anymore.. i will try to test as soon as i have access to a second screne

**Comment by sdeken** [comment]
We should avoid allowing the visualizer to be displayed outside the screen bounds.  I'd like to get this corrected for 0.9.5, but I think it might take more work so I'm marking as 1.0.

**Comment by akitchen** [comment]
I don't believe this issue is still active - please open a new issue if so
