### ISSUE TITLE
Visualizer can get covered by full-screen windows

### ISSUE THREAD

**Issue by xanderdunn** [keycastr/keycastr#37]
The key strokes only appear for me on the first space of my first display.  All other spaces and displays don't show anything.  This makes it had to capture a screen recording of a visual bug that would occur, for example, only in a app that's full screen (which is a new space).

**Comment by akitchen** [comment]
Hey @xanderdunn , thanks for opening this issue.  I hope to look into this at some point.

**Comment by akitchen** [comment]
@xanderdunn for me it works across all spaces - could you try again with the latest version?

**Comment by nuflowx** [comment]
I just installed it and in fullscreen apps I can't see screens. Only on my first desktop, additional desktops don't show the keys as well.

So only desktop 1 works.

**Comment by akitchen** [comment]
you wouldn't expect to see it in a fullscreen app.  Displaying over fullscreen apps would be an interesting enhancement though.

**Comment by parisk** [comment]
Being able to view keyboard shortcuts in fullscreen mode would be fantastic for screencasts. Screencasting a full screen application helps you get rid of the OS chrome and displaying keyboard shortcuts on top of the pure content sounds amazing.

Is there anything we could do to help implementing this feature?

**Comment by mscuthbert** [comment]
Indeed, looking at this thread: https://feedback.techsmith.com/techsmith/topics/keystroke_recording -- you can see how much people are looking for ways of displaying keystrokes on screencasts.  Thanks! This is great!

**Comment by utensil** [comment]
It's possible to view keyboard shortcuts in fullscreen mode. Here's how I made it work:

* start keycastr (at this time, it can only show keystrokes on the first screen)
* switch to a fullscreen app on another screen(terminal, sublime text and such)
* type key and nothing shows
* open preference of keycastr (on the top)
* change visualizer to Svelte and change it back to default
* it magically works!

**Comment by nuflowx** [comment]
For me it was enough to start keyCastr whilst in the Fullscreen-App.

Your workaround also works, thanks! :). The only thing is it is limited to one screen only. So if it works in one Fullscreen-location it will only work there.

But still great that it's possible ^^)

**Comment by sdeken** [comment]
Given the workaround steps [described by utensil](https://github.com/keycastr/keycastr/issues/37#issuecomment-213667782), it seems to me that we should be able to detect that we're being covered by a fullscreen app and re-create the window (or whatever).  Marking for 1.0!

**Comment by parisk** [comment]
That's great news. Thanks!

**Comment by sdeken** [comment]
Looks like we can get sort of halfway there by setting collectionBehavior to canJoinAllSpaces | stationary, which allows the visualizer window to be displayed on all screens.  I can't see a way to get the visualizer window to be displayed over a fullscreen window, even just a maximized browser window.  It may take some doing, but we'll find a way to make it happen.

`    _visualizerWindow.collectionBehavior = NSWindowCollectionBehaviorCanJoinAllSpaces | NSWindowCollectionBehaviorStationary;`
`    _visualizerWindow.level = kCGAssistiveTechHighWindowLevelKey;`

**Comment by tbodt** [comment]
Any update on this? @sdeken

**Comment by akitchen** [comment]
#108 made it so that I could see KeyCastr over a fullscreen window on macOS 10.13.4

To be released in v0.9.6

**Comment by Aariq** [comment]
Still having trouble with this in version 0.9.12.  I can't drag the display over to a fullscreen app on an external display.
