### ISSUE TITLE
Case sensitivity or Shift modifier awareness

### ISSUE THREAD

**Issue by scooter-dangle** [keycastr/keycastr#43]
How possible would it be to display the capital versions of letters (and `shift`ed symbols) when Shift+key is pressed?

It's possible that KeyCastr *does* display this as capital letters / `shift`ed symbols and that I'm only missing out due to my Karabiner Shift key overrides. (*Do* other people see capital letters display when they enter them?)

**Comment by akitchen** [comment]
please see the changes in v0.9.1.  Thanks!

**Comment by scooter-dangle** [comment]
That's awesome! Makes it much easier to share I'm doing in Vim! Thanks!
