### ISSUE TITLE
Doesn't work on yosemite ?

### ISSUE THREAD

**Issue by mirzalazuardi** [keycastr/keycastr#44]
Hello, I really appriciated about this project. 
It will help me at creating my screencast for video tutorial.

I already installed keycastr via brew on my Mac OS X ( Yosemite ).
And I ran the application. I don't know if i missing something or what.
I'm using the svelte visualizer, because i'm confused about the default visualizer(nothing happens).
when i use svelte visualizer the blackbox appears, and shift,control,option and command button respond to it, but i don't see other button(e.g control C, it should appear ^ C ). 

Can you help me about this issue / bug  ? 

Thanks

**Comment by zxqfox** [comment]
Just installed it on Yosemite, all is fine.
