### ISSUE TITLE
Wrong hotkey displayed in menu

### ISSUE THREAD

**Issue by qfox** [keycastr/keycastr#45]
There are 2 different combinations in prefs and in menu.
The one in prefs is right. Need to sync menu somehow with it.

![](https://leto13e.storage.yandex.net/rdisk/d04fe356ca6553067937bbdc2138337e7b74c6181cc8320636614f33808ab7e0/inf/MClB7ayG4vKX4vswtwp7o1ICMaL8mwP8dXufo7powL6_45unxTGIFZOriD_U0EJtRmR_0fePyGwwW_WKW0_CEA==?uid=0&filename=Monosnap%202015-12-02%2013-23-55.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=c0ea9a4720fac4ac07ba6aa61fda0274&force_default=no&ycrid=na-c0d9f384853a6a1ded67fbe0a081e4d6-downloader3g)

**Comment by sdeken** [comment]
This image has been reaped, can you show me again?  Seems like an easy fix if we can confirm it, and I'd like to get it in for 0.9.5.  Thanks!

**Comment by sdeken** [comment]
I can confirm this myself now - when the main key used for the shortcut is a letter, the menu item appears to always show shift, whether or not shift is part of the hotkey used to toggle capturing.  Not sure what's causing this - we appear to set the modifiers correctly, but the menu shows shift regardless.  Very odd!

**Comment by akitchen** [comment]
I believe this is fixed in #98
