### ISSUE TITLE
Doesn't show SHIFT, OPTION, or COMMAND

### ISSUE THREAD

**Issue by PierBover** [keycastr/keycastr#48]
What the title says. When pressing those keys individually nothing appears.

I need to record a screen using those keys along with the mouse. For example Illustrator (and most graphics software) when using OPTION and dragging an object it duplicates it, or when using SHIFT it constraints the movement and rotation of an object. But those keystrokes do not appear.

I'm on 10.11.2

**Comment by akitchen** [comment]
You should try the Svelte visualizer for this - it has the behavior you want.

**Comment by PierBover** [comment]
Oh thanks.

It would be great is Svelte had a preference to make it bigger.
