### ISSUE TITLE
Cannot install via Homebrew

### ISSUE THREAD

**Issue by DoWhileGeek** [keycastr/keycastr#49]
Just found this project, followed the install instructions on the landing, and ran into this issue.

```bash
~/Documents/Workspace $ brew install Caskroom/cask/keycastr
==> brew cask install Caskroom/cask/keycastr
Error: Cask 'keycastr' definition is invalid: Bad header line: parse failed
```

Any clue whats going on?

**Comment by codeHatcher** [comment]
+1, same problem for me

**Comment by akitchen** [comment]
have you tried ```brew cask install keycastr``` ?

Worked for me on a freshly installed homebrew.

**Comment by DoWhileGeek** [comment]
@akitchen `Error: Cask 'keycastr' definition is invalid: Bad header line: parse failed`

**Comment by akitchen** [comment]
Is brew doctor otherwise happy? It worked for me.

**Comment by srustamo** [comment]
Had the same issue. Try `brew update && brew uninstall --force brew-cask`. Details are [here](https://github.com/Homebrew/homebrew/issues/46850).

**Comment by akitchen** [comment]
Thanks very much for the info.  @DoWhileGeek @codeHatcher  please give it a whirl and let us know.  The cask recipe passes their lint and worked for me, so I'm pretty sure it's not an issue with KeyCastr

In the meantime, please feel free to grab a release from the GitHub releases page https://github.com/keycastr/keycastr/releases/download/v0.9.2/KeyCastr.app.zip

**Comment by patrick91** [comment]
```brew cask install keycastr```

worked for me :)

**Comment by akitchen** [comment]
Thanks for validating -- that's been my experience as well.

**Comment by akitchen** [comment]
Please open a new issue if this persists - we believe it to be fixed and have validated.
