### ISSUE TITLE
Please commit Xcode project files

### ISSUE THREAD

**Issue by ruurd** [keycastr/keycastr#53]
Please commit Xcode project files

**Comment by akitchen** [comment]
Hello,

What files do you believe to be missing? I think this issue can be closed...

**Comment by ruurd** [comment]
xxx.xcodeproj and/or xxx.xcworkspace

**Comment by ruurd** [comment]
That would make it possible to quickly get up to speed hacking on it

**Comment by sdeken** [comment]
Those files are already committed here: https://github.com/keycastr/keycastr/tree/master/keycastr/KeyCastr.xcodeproj

**Comment by ruurd** [comment]
Duh. STUPID mode... Sorry.

**Comment by sdeken** [comment]
No worries mate, we've all been there!

**Comment by ruurd** [comment]
Meh. Returning there after 20 years... :-( Sometimes I'm utterly hopeless...
