### ISSUE TITLE
Svelte doesn't display individual char key presses

### ISSUE THREAD

**Issue by vishusingh** [keycastr/keycastr#55]
Title sums it up, svelte ignores all key presses, default view doesn't  show only command key presses, this is slightly frustrating as none of the modes serves the full purpose when creating screencasts that need all the inputs to be shown, e.g. char binding hotkeys in Sketch/Photoshop.

**Update**: Please ignore/delete this as I noticed this is a duplicate of enhancement request #17

**Comment by akitchen** [comment]
Thanks!
