### ISSUE TITLE
Mismapping Azerty/Qwerty

### ISSUE THREAD

**Issue by ZorGleH** [keycastr/keycastr#56]
Hi,

I'm using an Azerty keyboard on latest OSX and latest keycastr to date. When I type "W" (major double w), it displays "Z". And vice-versa. Not the case for minor "z" or "w".

End of report :+1:

**Comment by scottopell** [comment]
Same thing happens for Dvorak Keyboards.

Uppercase `w` and `h` display as `<` and `J` respectively.

**Comment by scottopell** [comment]
I don't have XCode installed so I can't test this right now, but I have a theory that the problem is somewhere in these few lines of code

```objc
    TISInputSourceRef inputSource = TISCopyCurrentKeyboardLayoutInputSource();

    CFDataRef layoutData = TISGetInputSourceProperty(inputSource, kTISPropertyUnicodeKeyLayoutData);
    const UCKeyboardLayout *keyboardLayout = (const UCKeyboardLayout *)CFDataGetBytePtr(layoutData);
```
https://github.com/keycastr/keycastr/blob/master/keycastr/KCKeyboardTap.m#L216

I'll try to get XCode setup in the next few days and try out some different combinations.

Other projects seem to be using TISCopyCurrentKeyboardInputSource instead of TISCopyCurrentKeyboard**Layout**InputSource

https://github.com/alexandrudima/vscode-keyboard/blob/76c940ef6996254f10e3ee5cc642d98dfa004b7f/src/keyboard_mac.mm#L61

**Comment by kirbyk** [comment]
Hey @scottopell I haven't taken the time to really look into this bug.

I went ahead and tested your potential solution and changing `TISCopyCurrentKeyboardLayoutInputSource` to `TISCopyCurrentKeyboardInputSource` results in the same issues on Dvorak.

Hopefully I can investigate later today and track down the issue. 👀

**Comment by Crocmagnon** [comment]
This issue still affects me as well. Any update on a fix ? 😃

**Comment by Bohrbug** [comment]
Same thing for programmer Dvorak. Would love to see fix. 😅

**Comment by sdeken** [comment]
Definitely a bug, I'll slate it for the 0.9.5 release and get it fixed

**Comment by vbauerster** [comment]
I use https://github.com/vbauerster/DeepDvorak layout, and have the same issue.

**Comment by rawaludin** [comment]
Same thing for Colemak user here :)

**Comment by wincent** [comment]
@rawaludin: See the links to my commits above. I've hacked around the issue on Colemak, although in a totally non-general way:

- https://github.com/wincent/keycastr/commit/50479653c28815359d1f88973741dcfbb6483691
- https://github.com/wincent/keycastr/commit/100230f3a9a10554f218977b6e9ce9e872b9ce07

**Comment by pierpo** [comment]
Still having the issue when using azerty. Not with the alphanumeric characters, but with the special characters.

For example : 
- `*` is mismatched as `}`
-  `%` is mismatched as `"`

**Comment by akitchen** [comment]
Thanks for trying it out. I would like to see if there's a way to map / decode these using native APIs as opposed to the hard-coded dictionary solution currently in place.

**Comment by serverwentdown** [comment]
+1

For now, here's mappings for programmer Dvorak:
https://github.com/serverwentdown/keycastr/blob/master/keycastr/KCKeystrokeTransformer.m

>

**Comment by akitchen** [comment]
If anyone is interested in trying out this fix & providing feedback, please try out the build located here:

https://github.com/akitchen/keycastr/blob/cb400401c0576798a4cddc2fbe12040e944a055b/keycastr/bin/KeyCastr.app.zip

**Comment by Crocmagnon** [comment]
@akitchen, when I try to launch your app I get this error window
![Error window](https://www.dropbox.com/s/ip5wpxbudtwxm4w/Capture%20d%27%C3%A9cran%202017-08-02%2014.02.51.png?raw=1)

When I click on "Grant Access", it prompts me for my password, then exits and restarts the app with the same error window.

**Comment by pierpo** [comment]
@akitchen Works for me! Thanks :)
