### ISSUE TITLE
Feature request: Show keys in 'C-x' 'M-x' 'C-M-x' 'SPC' style.

### ISSUE THREAD

**Issue by jiegec** [keycastr/keycastr#59]
This syntax comes from Emacs: https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Sequences.html#Key-Sequences. I think it would look great for those recording Emacs videos especially tutorial ones.

**Comment by sdeken** [comment]
Ideally I'd like to see this implemented as a new visualizer - the intent was to allow visualizers to be developed by third parties and installed by the user, but I don't know that it ever made it into the product.  I agree it would be useful!

**Comment by alexjgriffith** [comment]
You have to overwrite variables defined in `KCKeystrokeTransformer.m`

``` 
static NSString* kCommandKeyString = @"\xe2\x8c\x98";
// static NSString* kAltKeyString = @"\xe2\x8c\xa5";
static NSString* kAltKeyString = @"M-";
// static NSString* kControlKeyString = @"\xe2\x8c\x83";
static NSString* kControlKeyString = @"C-";
// static NSString* kShiftKeyString = @"\xe2\x87\xa7";
static NSString* kShiftKeyString = @"S-;
// static NSString* kLeftTabString = @"\xe2\x87\xa4";
static NSString* kAltKeyString = @"M-";
```
Also check out `_specialKeys` in the same file (~ L7), it will let you change the symbols used for space return etc


You can rebuild the whole project with the new bindings in xcode. I'm not familiar enough with this project or objective c to be sure if there is an idiomatic way to do this in a plugin.
