### ISSUE TITLE
Command shortcuts not displaying, ^A instead

### ISSUE THREAD

**Issue by quicksnap** [keycastr/keycastr#6]
Whenever I attempt to do a command shortcut, using any keyboard combinations, I get this: http://dl.dropbox.com/u/6604937/Screenshots/yoz_o513khob.png

I have no idea..

I'm on 10.7.5. Anything else I can provide? Normal text shows up fine, just not combinations using CMD/Option/Ctrl.

**Comment by aaronjensen** [comment]
I'm getting this now on OSX 10.10.3

It works fine w/ svelte but the default formatter is wrong.
