### ISSUE TITLE
Conflict with iTerm 2

### ISSUE THREAD

**Issue by ynyounuo** [keycastr/keycastr#61]
Same thing as #25 
But I find out when iTerm 2 is open, Keycastr are not able to work on OS X.

**Comment by ynyounuo** [comment]
Disable the **Secure Keyboard Entry** solves this.
<img width="305" alt="screen shot 2016-05-04 at 00 21 13" src="https://cloud.githubusercontent.com/assets/6180046/15007476/35f0a7e6-118e-11e6-8b0c-9906573daccc.png">

So, in a way, [**Secure Event Input**](https://developer.apple.com/library/mac/technotes/tn2150/_index.html) maybe the reason. Some other apps like kaspersky and terminal which use this function may cause KeyCastr unable to work.

**Comment by sonph** [comment]
@ynyounuo thanks a lot for this! I've been trying to get keycastr to work for a while now but only the modifier keys are shown. Maybe this should be added to the readme or wiki.

**Comment by AdamMomen** [comment]
@ynyounuo Thanks a million, it's been bugging me for months, it feels like rock removed out from my chest to this to work. ❤️
