### ISSUE TITLE
I get catastrophic error encountered even after reinstalling the app 

### ISSUE THREAD

**Issue by nikitavoloboev** [keycastr/keycastr#66]
I get this screen every time the app starts up now : 

![2016-08-31 at 18 44](https://cloud.githubusercontent.com/assets/6391776/18137957/e7084424-6faa-11e6-866e-ad1528aaa348.png)

I have activated the accessibility setting for the app and this error is still there.

What should I do?

**Comment by akitchen** [comment]
As the instructions in the dialog box indicate, you need to re-add KeyCastr
to the list of apps allowed to control your computer.

Modern versions of OS X require this whenever the settings of the app
change, and we haven't yet gotten around to automating it.

**Comment by nikitavoloboev** [comment]
Isn't this the place where you add it? 

![2016-08-31 at 20 06](https://cloud.githubusercontent.com/assets/6391776/18140581/763fa604-6fb6-11e6-854e-feaa30bf0a35.png)

I have it ticked and yet the error still shows.

**Comment by akitchen** [comment]
Yes, however you need to remove the icon and re-add it by dragging it in. Un-ticking/re-ticking the box isn't enough, unfortunately.

**Comment by nikitavoloboev** [comment]
I am not quite sure what you mean by 'remove the icon'. Do you mean to move keycastr out of /Applications and back in?

**Comment by nikitavoloboev** [comment]
This works, thank you. This is a really great little utility.

**Comment by gozyf** [comment]
OS Catalina: the same problem, even if I re-add it by dragging, it shows the error

**Comment by dtkachev** [comment]
To resolve this error you need to add permissions in:
Privacy -> Accessibility -> KeyCastr
<img width="584" alt="Privacy -  Accessibility -  KeyCastr" src="https://user-images.githubusercontent.com/2193089/71357492-0c9b1180-2597-11ea-9e9a-4d59a2b8afe5.png">
Privacy -> Input Monitoring -> KeyCastr
<img width="581" alt="Privacy -  Input Monitoring -  KeyCastr" src="https://user-images.githubusercontent.com/2193089/71357491-0c9b1180-2597-11ea-9385-f4ed19b33e7c.png">

**Comment by fjoachim** [comment]
Seeing the error dialog even after adding KeyCastr to both **Accessibility** and **Input Monitoring** on macOS 10.15.4.

**Comment by akitchen** [comment]
Input Monitoring shouldn't be necessary, it works fine for me without it. 

I have seen this issue go away in Catalina after rebooting, but I'm not sure that's the solution. Perhaps those changes in settings aren't always applied immediately.

**Comment by akitchen** [comment]
On Catalina, I did the following to reset the permissions:

- remove KeyCastr from the list of applications with Accessibility permissions
- double-check that KeyCastr isn't in the list of applications with Input Monitoring permissions
- reboot to ensure all internal permissions updates are applied/synchronized

After rebooting, when starting KeyCastr it shows the error screen and offers to open the Security & Privacy preferences pane as expected. MacOS also displays an additional prompt about Input Monitoring. KeyCastr is already listed in the Input Monitoring list, but isn't selected. After checking the box next to KeyCastr in the Input Monitoring list, everything works fine on next app startup.

It should be possible to refactor the app startup routine to handle this more gracefully, which we'll do in an upcoming release.
