### ISSUE TITLE
This would appear to be broken with MacOIS Sierra

### ISSUE THREAD

**Issue by pquodling** [keycastr/keycastr#69]
Installing  via HOmebrew cask. 
brew cask install --force keycastr
==> Downloading https://github.com/keycastr/keycastr/releases/download/v0.9.2/KeyCastr.app.zip
######################################################################## 100.0%
==> Verifying checksum for Cask keycastr
==> Moving App 'KeyCastr.app' to '/Applications/KeyCastr.app'
==> Enabling accessibility access
Password:
==> Error: attempt to write a readonly database
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/bin/sqlite3", "#<Pathname:/Library/Application Support/com.apple.TCC/TCC.db>", "INSERT OR REPLACE INTO access VALUES('kTCCServiceAccessibility','net.stephendeken.KeyCastr',0,1,1,NULL,NULL);"]

==> Standard Output of failed command:

==> Standard Error of failed command:
Error: attempt to write a readonly database

==> Exit status of failed command:
#<Process::Status: pid 59874 exit 8>
Peters-iMac-2:~ peter$

**Comment by akitchen** [comment]
Perhaps. But this is an issue in homebrew cask, not KeyCastr

**Comment by akitchen** [comment]
To follow up, you should still be able to install it manually from the releases page on github ([link](https://github.com/keycastr/keycastr/releases)). 

Personally I haven't had a chance to install the latest OS X yet, so any add'l feedback once you get it running would be much appreciated!
