### ISSUE TITLE
Alt + Space shows twice

### ISSUE THREAD

**Issue by connercowling** [keycastr/keycastr#83]
Alt + Space will generate two Keycastr views:

![double-show](https://cloud.githubusercontent.com/assets/3486466/25627399/0f9b3026-2f28-11e7-8a67-020f6b5f4f1b.gif)

As far as I can tell....

This does not occur with other uses of Alt:

![alt-usage](https://cloud.githubusercontent.com/assets/3486466/25627433/30929be8-2f28-11e7-8ea0-03802ef7743a.gif)

Or with other uses of space:

![space-usage](https://cloud.githubusercontent.com/assets/3486466/25627446/39a69eb4-2f28-11e7-9e5b-cfff00f0ffa3.gif)

**Comment by akitchen** [comment]
I can't reproduce this in the latest version - please reopen if this is still happening for you
