### ISSUE TITLE
KeyCastr - Getting to the preferences screen

### ISSUE THREAD

**Issue by gprasant** [keycastr/keycastr#84]
I just installed KeyCastr and I have a problem when trying to go to Keycastr's preferences window. 

![keycastr-preferences](https://raw.githubusercontent.com/keycastr/keycastr/master/assets/preferences.png)

Clicking on the dock icon only shows me these options: 
<img width="339" alt="screen shot 2017-05-04 at 10 21 16 am" src="https://cloud.githubusercontent.com/assets/212911/25716313/7f975882-30b3-11e7-9d5f-c6b759a9e2d8.png">

I don't see the app's icon on the menu bar on top.
<img width="1162" alt="screen shot 2017-05-04 at 10 23 42 am" src="https://cloud.githubusercontent.com/assets/212911/25716756/14169bb6-30b5-11e7-97b5-089b94d6034b.png">

I also don't see the app icon in the app switcher (When I press `Cmd + Tab`)

-----

_How Can I get to the preferences window ?_

**Comment by akitchen** [comment]
You can open it from the KeyCastr menu item when the app is in the foreground, or with cmd-,
