### ISSUE TITLE
Doesn't capture Cmd & Shift & MouseClick key combo on the Mac

### ISSUE THREAD

**Issue by reenamn** [keycastr/keycastr#85]
Hi, I love this Keycastr. Works great. I was recording a tutorial and noticed today it didn't pick up 
Cmd & Shift & MouseClick key combo. 

In InDesign, this key combo is used to Override / Unlock Master Page Items.

Is there any way that this can be picked up by Keycastr in the next iteration?

**Comment by zbstof** [comment]
Have the same problem for IDE. Control+Click is a navigation shortcut

**Comment by filipgoc** [comment]
+ 1. Also a problem for me when demonstrating CAD software.

**Comment by JohnSlaughter** [comment]
MouseCastr?

+1 for a mouse Key HUD in the other corner.

**Comment by akitchen** [comment]
These use cases should be covered by the mouse visualizer functionality. More creative or specific ideas could be proposed separately. Thanks
