### ISSUE TITLE
The keycastr icon never shows in dock.

### ISSUE THREAD

**Issue by cmal** [keycastr/keycastr#87]
I change the `keycastr` pereference `show in menubar` to `show in dock`,
and now I cannot find `keycastr` any more, neighter in menubar nor in dock.

But I can still see my key press in the bottom left of my screen, just cannot find the icon.

Btw, I am using `Mac OS X 10.11.6`.

**Comment by akitchen** [comment]
Glad to hear it's working OK - It sounds like you might need to drag it from the Applications folder onto the dock yourself.
