### ISSUE TITLE
Keycastr can't acquire permissions

### ISSUE THREAD

**Issue by achikin** [keycastr/keycastr#92]
When I start an application this screen pops up
<img width="423" alt="screen shot 2017-07-17 at 13 20 47" src="https://user-images.githubusercontent.com/611419/28268472-15c318ae-6b07-11e7-9f45-31df67c10da0.png">
When I press `Grant Access` button the password prompt appears and when I enter my password `Catastrophic error` screen appears again and the process repeats itself.

KeyCastr version 0.9.4 installed with brew cask.

MacOSX 10.12.5

**Comment by achikin** [comment]
I managed to reproduce the issue on the app downloaded directly from github.

**Comment by achikin** [comment]
Managed to fix that partially by going to `Security & Privacy` -> `Accessibility` and adding KeyCastr to the list manually
![screen shot 2017-07-17 at 16 17 13](https://user-images.githubusercontent.com/611419/28269720-b6b2d3b8-6b0b-11e7-836d-1bc37df0a489.png)

**Comment by tsheaff** [comment]
This is a pretty fundameltal issue, is it recent?

**Comment by achikin** [comment]
I can't tell exactly. I've installed it for the first time 3 days ago.

**Comment by akitchen** [comment]
Changes in recent versions of OS X / macOS are probably a factor here. For example, homebrew cask currently isn't able to automate these permissions either, so one must add the app to the accessibility list manually.

**Comment by akitchen** [comment]
The README has been updated to address this.
