### ISSUE TITLE
Support other functions keys like F17 F18

### ISSUE THREAD

**Issue by yqrashawn** [keycastr/keycastr#99]
They are now question marks. ![screen shot 2017-10-10 at 4 34 39 pm](https://user-images.githubusercontent.com/15090582/31376982-3c0364b8-ad6c-11e7-8250-3621182a9c3e.png)

**Comment by akitchen** [comment]
Yes, I completely agree :)

If anyone is interested in making a pull request, this could be a reasonable first contribution to the project
